#ifndef XTBLOOM_RUNTIME_BACKEND_HPP
// xtbloom's CUDA/MKL additional permission is in CUDA_MKL_LINKING_EXCEPTION.

#define XTBLOOM_RUNTIME_BACKEND_HPP

#include <cstdint>
#include <memory>
#include <string>

#include "xtbloom/xtbloom.h"

namespace xtbloom::detail {

class Gfn2CpuExecutionCache;
class Gfn2CudaExecutionCache;

/*
 * Internal CPU numerical policy selected once when a context is created.
 * This deliberately remains outside the stable public ABI: the environment
 * experiment can evolve without appending fields to xtbloom_context_options_t.
 */
enum class CpuPrecisionPolicy : std::uint8_t { kFloat64, kAdaptive };

/* Runtime state is opaque at the ABI boundary so backend internals can evolve. */
struct Context {
  xtbloom_backend_t backend = XTBLOOM_BACKEND_CPU;
  std::int32_t device_id = -1;
  std::int32_t cpu_threads = 0;
  CpuPrecisionPolicy cpu_precision = CpuPrecisionPolicy::kFloat64;
  void* stream = nullptr;

  /*
   * CPU contexts eagerly construct this execution state so the first compute
   * call cannot race cache initialization. The cache owns the fixed worker
   * pool selected by cpu_threads. shared_ptr permits the cache type to remain
   * incomplete here while Context is destroyed through the opaque C handle.
   * The executor serializes transactions while workers process independent
   * systems inside one transaction.
   */
  std::shared_ptr<Gfn2CpuExecutionCache> gfn2_cpu_execution_cache;

  /*
   * CUDA contexts likewise own one reusable fixed-topology GFN2 runtime.
   * The cache header deliberately contains no CUDA types, so this ownership
   * remains an incomplete-type boundary that a future HIP cache can mirror.
   * Public descriptor staging and execution are connected in #114; eager
   * construction here establishes the production context lifetime now.
   */
  std::shared_ptr<Gfn2CudaExecutionCache> gfn2_cuda_execution_cache;
};

xtbloom_status_t create_context(const xtbloom_context_options_t& options, Context*& context,
                                std::string& error);

#if defined(XTBLOOM_HAS_CUDA)
bool resolve_cuda_device(std::int32_t requested_device, std::int32_t& resolved_device,
                         std::string& error);

/* Upload immutable GFN2 tables once for each CUDA device used by this process. */
bool ensure_cuda_gfn2_parameters(std::int32_t device_id, std::string& error);

/* Internal observability used to prove that repeated contexts reuse the upload. */
std::uint64_t cuda_gfn2_parameter_upload_count(std::int32_t device_id);

/* Test hook that copies constant memory back and compares every generated byte. */
bool cuda_gfn2_parameters_match_host(std::int32_t device_id, std::string& error);
#endif

}  // namespace xtbloom::detail

#endif  // XTBLOOM_RUNTIME_BACKEND_HPP
