#include "model/gfn2/h0.hpp"

#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <numeric>
#include <string>
#include <vector>

#include "model/gfn2/basis.hpp"
#include "model/gfn2/coordination.hpp"
#include "model/gfn2/integrals.hpp"

#define CHECK(condition) \
  do {                   \
    if (!(condition)) {  \
      return __LINE__;   \
    }                    \
  } while (false)

namespace {

bool near(double actual, double expected, double tolerance) {
  return std::abs(actual - expected) <= tolerance;
}

struct Evaluation {
  xtbloom::detail::gfn2::BasisPlan basis;
  xtbloom::detail::gfn2::IntegralPlan integrals;
  xtbloom::detail::gfn2::CoordinationPlan coordination;
  xtbloom::detail::gfn2::H0Plan h0;
  std::vector<double> workspace;
};

bool make_evaluation(std::int64_t batch_size, const std::vector<std::int64_t>& atom_offsets,
                     const std::vector<std::int32_t>& atomic_numbers, Evaluation& evaluation,
                     std::string& error) {
  const auto total_atoms = static_cast<std::int64_t>(atomic_numbers.size());
  if (xtbloom::detail::gfn2::make_basis_plan(batch_size, total_atoms, atom_offsets.data(),
                                             atomic_numbers.data(), evaluation.basis,
                                             error) != XTBLOOM_STATUS_SUCCESS ||
      xtbloom::detail::gfn2::make_integral_plan(evaluation.basis, evaluation.integrals, error) !=
          XTBLOOM_STATUS_SUCCESS ||
      xtbloom::detail::gfn2::make_coordination_plan(batch_size, total_atoms, atom_offsets.data(),
                                                    atomic_numbers.data(), evaluation.coordination,
                                                    error) != XTBLOOM_STATUS_SUCCESS ||
      xtbloom::detail::gfn2::make_h0_plan(evaluation.basis, evaluation.integrals,
                                          atomic_numbers.data(), evaluation.h0,
                                          error) != XTBLOOM_STATUS_SUCCESS) {
    return false;
  }
  evaluation.workspace.resize((evaluation.integrals.workspace_size_bytes + sizeof(double) - 1u) /
                              sizeof(double));
  return true;
}

double contraction(const std::vector<double>& matrix, const std::vector<double>& weights) {
  return std::inner_product(matrix.begin(), matrix.end(), weights.begin(), 0.0);
}

bool evaluate_h0(const Evaluation& evaluation, const std::vector<double>& positions,
                 const std::vector<double>& coordination, const std::vector<double>& overlap,
                 std::vector<double>& hamiltonian, std::string& error) {
  hamiltonian.resize(static_cast<std::size_t>(evaluation.integrals.total_matrix_elements));
  return xtbloom::detail::gfn2::evaluate_h0_cpu(
             evaluation.basis, evaluation.integrals, evaluation.h0, positions.data(),
             coordination.data(), overlap.data(), hamiltonian.data(),
             error) == XTBLOOM_STATUS_SUCCESS;
}

bool evaluate_full(Evaluation& evaluation, const std::vector<double>& positions,
                   std::vector<double>& coordination, std::vector<double>& overlap,
                   std::vector<double>& hamiltonian, std::string& error) {
  coordination.resize(static_cast<std::size_t>(evaluation.basis.total_atoms));
  overlap.resize(static_cast<std::size_t>(evaluation.integrals.total_matrix_elements));
  if (xtbloom::detail::gfn2::evaluate_coordination_cpu(evaluation.coordination, positions.data(),
                                                       coordination.data(),
                                                       error) != XTBLOOM_STATUS_SUCCESS ||
      xtbloom::detail::gfn2::evaluate_overlap_cpu(
          evaluation.basis, evaluation.integrals, positions.data(), overlap.data(),
          evaluation.workspace.data(), evaluation.workspace.size() * sizeof(double),
          error) != XTBLOOM_STATUS_SUCCESS) {
    return false;
  }
  return evaluate_h0(evaluation, positions, coordination, overlap, hamiltonian, error);
}

int test_tblite_h2_and_lih_scaling_goldens() {
  /*
   * Coordinates and H0/overlap scaling matrices are from dxtb's Apache-2.0
   * test_hamiltonian/test_gfn2.py corpus, whose references were generated by
   * tblite 0.3.0. The formulas and relevant GFN2 parameters are unchanged in
   * the tblite 0.7.0 revision pinned by xtbloom.
   */
  const std::vector<std::int64_t> atom_offsets{0, 2, 4};
  const std::vector<std::int32_t> atomic_numbers{1, 1, 3, 1};
  const std::vector<double> positions{
      0.0, 0.0, -0.70252931147690, 0.0, 0.0, 0.70252931147690,
      4.0, 0.0, -1.50796743897235, 4.0, 0.0, 1.50796743897235,
  };
  Evaluation evaluation;
  std::string error;
  CHECK(make_evaluation(2, atom_offsets, atomic_numbers, evaluation, error));
  CHECK(evaluation.integrals.matrix_offsets == std::vector<std::int64_t>({0, 4, 29}));
  CHECK(evaluation.h0.shell_pair_offsets == std::vector<std::int64_t>({0, 4, 13}));

  std::vector<double> coordination(4);
  CHECK(xtbloom::detail::gfn2::evaluate_coordination_cpu(evaluation.coordination, positions.data(),
                                                         coordination.data(),
                                                         error) == XTBLOOM_STATUS_SUCCESS);
  std::vector<double> overlap(29, 1.0);
  std::vector<double> hamiltonian;
  CHECK(evaluate_h0(evaluation, positions, coordination, overlap, hamiltonian, error));

  constexpr std::array<double, 4> h2_reference{
      -3.91986886330804e-1,
      -7.10344830094570e-1,
      -7.10344830094570e-1,
      -3.91986886330804e-1,
  };
  constexpr std::array<double, 25> lih_reference{
      -1.85652593278629e-1, -1.32503346243859e-1, -1.32503346243859e-1, -1.32503346243859e-1,
      -5.11314980009571e-1, -1.32503346243859e-1, -7.93540992090888e-2, -7.93540992090888e-2,
      -7.93540992090888e-2, -5.67490975937946e-1, -1.32503346243859e-1, -7.93540992090888e-2,
      -7.93540992090888e-2, -7.93540992090888e-2, -5.67490975937946e-1, -1.32503346243859e-1,
      -7.93540992090888e-2, -7.93540992090888e-2, -7.93540992090888e-2, -5.67490975937946e-1,
      -5.11314980009571e-1, -5.67490975937946e-1, -5.67490975937946e-1, -5.67490975937946e-1,
      -3.91761150304657e-1,
  };
  for (std::size_t index = 0; index < h2_reference.size(); ++index) {
    CHECK(near(hamiltonian[index], h2_reference[index], 5.0e-14));
  }
  for (std::size_t index = 0; index < lih_reference.size(); ++index) {
    CHECK(near(hamiltonian[h2_reference.size() + index], lih_reference[index], 5.0e-14));
  }
  return 0;
}

int test_independent_h0_vjp() {
  const std::vector<std::int64_t> atom_offsets{0, 3};
  const std::vector<std::int32_t> atomic_numbers{8, 1, 1};
  std::vector<double> positions{0.13, -0.27, 0.08, 1.51, 0.31, -0.22, -0.44, 1.36, 0.57};
  std::vector<double> coordination{1.73, 0.91, 1.04};
  Evaluation evaluation;
  std::string error;
  CHECK(make_evaluation(1, atom_offsets, atomic_numbers, evaluation, error));

  const std::size_t matrix_size =
      static_cast<std::size_t>(evaluation.integrals.total_matrix_elements);
  std::vector<double> overlap(matrix_size);
  std::vector<double> weights(matrix_size);
  for (std::size_t index = 0; index < matrix_size; ++index) {
    overlap[index] = 0.07 + 0.013 * static_cast<double>((index * 7u) % 19u);
    weights[index] = -0.4 + 0.031 * static_cast<double>((index * 11u) % 23u);
  }

  std::vector<double> hamiltonian;
  CHECK(evaluate_h0(evaluation, positions, coordination, overlap, hamiltonian, error));
  std::vector<double> dE_doverlap(matrix_size, 0.0);
  std::vector<double> dE_dcn(3, 0.0);
  std::vector<double> gradients(9, 0.0);
  CHECK(xtbloom::detail::gfn2::add_h0_vjp_cpu(evaluation.basis, evaluation.integrals, evaluation.h0,
                                              positions.data(), coordination.data(), overlap.data(),
                                              weights.data(), dE_doverlap.data(), dE_dcn.data(),
                                              gradients.data(), error) == XTBLOOM_STATUS_SUCCESS);

  constexpr double matrix_step = 1.0e-6;
  for (std::size_t element = 0; element < matrix_size; ++element) {
    overlap[element] += matrix_step;
    std::vector<double> right;
    CHECK(evaluate_h0(evaluation, positions, coordination, overlap, right, error));
    overlap[element] -= 2.0 * matrix_step;
    std::vector<double> left;
    CHECK(evaluate_h0(evaluation, positions, coordination, overlap, left, error));
    overlap[element] += matrix_step;
    const double numerical =
        (contraction(right, weights) - contraction(left, weights)) / (2.0 * matrix_step);
    CHECK(near(dE_doverlap[element], numerical, 2.0e-9));
  }

  constexpr double cn_step = 1.0e-6;
  for (std::size_t atom = 0; atom < coordination.size(); ++atom) {
    coordination[atom] += cn_step;
    std::vector<double> right;
    CHECK(evaluate_h0(evaluation, positions, coordination, overlap, right, error));
    coordination[atom] -= 2.0 * cn_step;
    std::vector<double> left;
    CHECK(evaluate_h0(evaluation, positions, coordination, overlap, left, error));
    coordination[atom] += cn_step;
    const double numerical =
        (contraction(right, weights) - contraction(left, weights)) / (2.0 * cn_step);
    CHECK(near(dE_dcn[atom], numerical, 2.0e-9));
  }

  constexpr double position_step = 2.0e-6;
  for (std::size_t coordinate = 0; coordinate < positions.size(); ++coordinate) {
    positions[coordinate] += position_step;
    std::vector<double> right;
    CHECK(evaluate_h0(evaluation, positions, coordination, overlap, right, error));
    positions[coordinate] -= 2.0 * position_step;
    std::vector<double> left;
    CHECK(evaluate_h0(evaluation, positions, coordination, overlap, left, error));
    positions[coordinate] += position_step;
    const double numerical =
        (contraction(right, weights) - contraction(left, weights)) / (2.0 * position_step);
    CHECK(near(gradients[coordinate], numerical, 3.0e-9));
  }
  for (std::size_t axis = 0; axis < 3; ++axis) {
    CHECK(near(gradients[axis] + gradients[3u + axis] + gradients[6u + axis], 0.0, 2.0e-15));
  }
  return 0;
}

int test_composed_coordinate_vjp() {
  const std::vector<std::int64_t> atom_offsets{0, 3};
  const std::vector<std::int32_t> atomic_numbers{8, 1, 1};
  std::vector<double> positions{0.08, -0.04, 0.11, 1.47, 0.22, -0.31, -0.36, 1.41, 0.52};
  Evaluation evaluation;
  std::string error;
  CHECK(make_evaluation(1, atom_offsets, atomic_numbers, evaluation, error));

  std::vector<double> coordination;
  std::vector<double> overlap;
  std::vector<double> hamiltonian;
  CHECK(evaluate_full(evaluation, positions, coordination, overlap, hamiltonian, error));
  const std::size_t matrix_size = hamiltonian.size();
  std::vector<double> weights(matrix_size);
  for (std::size_t index = 0; index < matrix_size; ++index) {
    weights[index] = -0.21 + 0.017 * static_cast<double>((index * 13u) % 29u);
  }

  std::vector<double> dE_doverlap(matrix_size, 0.0);
  std::vector<double> dE_dcn(3, 0.0);
  std::vector<double> gradients(9, 0.0);
  CHECK(xtbloom::detail::gfn2::add_h0_vjp_cpu(evaluation.basis, evaluation.integrals, evaluation.h0,
                                              positions.data(), coordination.data(), overlap.data(),
                                              weights.data(), dE_doverlap.data(), dE_dcn.data(),
                                              gradients.data(), error) == XTBLOOM_STATUS_SUCCESS);
  CHECK(xtbloom::detail::gfn2::add_overlap_gradient_cpu(
            evaluation.basis, evaluation.integrals, positions.data(), dE_doverlap.data(),
            gradients.data(), evaluation.workspace.data(),
            evaluation.workspace.size() * sizeof(double), error) == XTBLOOM_STATUS_SUCCESS);
  CHECK(xtbloom::detail::gfn2::add_coordination_gradient_cpu(
            evaluation.coordination, positions.data(), dE_dcn.data(), gradients.data(), error) ==
        XTBLOOM_STATUS_SUCCESS);

  constexpr double step = 2.0e-5;
  for (std::size_t coordinate = 0; coordinate < positions.size(); ++coordinate) {
    positions[coordinate] += step;
    std::vector<double> right_coordination;
    std::vector<double> right_overlap;
    std::vector<double> right_hamiltonian;
    CHECK(evaluate_full(evaluation, positions, right_coordination, right_overlap, right_hamiltonian,
                        error));
    positions[coordinate] -= 2.0 * step;
    std::vector<double> left_coordination;
    std::vector<double> left_overlap;
    std::vector<double> left_hamiltonian;
    CHECK(evaluate_full(evaluation, positions, left_coordination, left_overlap, left_hamiltonian,
                        error));
    positions[coordinate] += step;
    const double numerical =
        (contraction(right_hamiltonian, weights) - contraction(left_hamiltonian, weights)) /
        (2.0 * step);
    CHECK(near(gradients[coordinate], numerical, 2.0e-8));
  }
  for (std::size_t axis = 0; axis < 3; ++axis) {
    CHECK(near(gradients[axis] + gradients[3u + axis] + gradients[6u + axis], 0.0, 2.0e-12));
  }
  return 0;
}

int test_validation() {
  const std::vector<std::int64_t> atom_offsets{0, 2};
  const std::vector<std::int32_t> atomic_numbers{1, 1};
  const std::vector<double> positions{0.0, 0.0, -0.7, 0.0, 0.0, 0.7};
  Evaluation evaluation;
  std::string error;
  CHECK(make_evaluation(1, atom_offsets, atomic_numbers, evaluation, error));
  std::vector<double> coordination(2, 0.8);
  std::vector<double> overlap(4, 1.0);
  std::vector<double> hamiltonian(4);

  auto corrupt = evaluation.h0;
  corrupt.shell_pair_offsets[1] -= 1;
  CHECK(xtbloom::detail::gfn2::evaluate_h0_cpu(
            evaluation.basis, evaluation.integrals, corrupt, positions.data(), coordination.data(),
            overlap.data(), hamiltonian.data(), error) == XTBLOOM_STATUS_INVALID_ARGUMENT);
  CHECK(xtbloom::detail::gfn2::evaluate_h0_cpu(evaluation.basis, evaluation.integrals,
                                               evaluation.h0, positions.data(), coordination.data(),
                                               overlap.data(), nullptr,
                                               error) == XTBLOOM_STATUS_INVALID_ARGUMENT);
  overlap[0] = std::numeric_limits<double>::quiet_NaN();
  CHECK(xtbloom::detail::gfn2::evaluate_h0_cpu(evaluation.basis, evaluation.integrals,
                                               evaluation.h0, positions.data(), coordination.data(),
                                               overlap.data(), hamiltonian.data(),
                                               error) == XTBLOOM_STATUS_INVALID_ARGUMENT);
  overlap[0] = 1.0;

  std::vector<double> coincident_positions(6, 0.0);
  std::vector<double> weights(4, 1.0);
  std::vector<double> dE_doverlap(4, 0.0);
  std::vector<double> dE_dcn(2, 0.0);
  std::vector<double> gradients(6, 0.0);
  CHECK(xtbloom::detail::gfn2::add_h0_vjp_cpu(
            evaluation.basis, evaluation.integrals, evaluation.h0, coincident_positions.data(),
            coordination.data(), overlap.data(), weights.data(), dE_doverlap.data(), dE_dcn.data(),
            gradients.data(), error) == XTBLOOM_STATUS_INVALID_ARGUMENT);

  const std::vector<std::int32_t> mismatched_atomic_numbers{1, 2};
  xtbloom::detail::gfn2::H0Plan mismatched;
  CHECK(xtbloom::detail::gfn2::make_h0_plan(evaluation.basis, evaluation.integrals,
                                            mismatched_atomic_numbers.data(), mismatched,
                                            error) == XTBLOOM_STATUS_INVALID_ARGUMENT);
  return 0;
}

}  // namespace

int main() {
  if (const int status = test_tblite_h2_and_lih_scaling_goldens(); status != 0) {
    return status;
  }
  if (const int status = test_independent_h0_vjp(); status != 0) {
    return status;
  }
  if (const int status = test_composed_coordinate_vjp(); status != 0) {
    return status;
  }
  return test_validation();
}
