// gpuxtb CPU SCC trace capture for the pinned tblite corpus (issues #49/#50).
//
// Reads a corpus case.spec (the same fixed layout emitted by
// generate_scc_corpus.py), runs the production CPU GFN2 SCC driver one
// iteration at a time, and streams the captured per-iteration state in exactly
// the same raw layout as the Fortran tblite recorder so that
// generate_scc_corpus.canonicalize() can assemble a gpuxtb-scc-trace-v1
// document and the comparator can compare it against the pinned golden.
//
// This executable is test-only tooling against internal GFN2 headers; it is
// not part of the public C ABI.
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <memory>
#include <new>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include "gpuxtb/gpuxtb.h"
#include "model/gfn2/aes2.hpp"
#include "model/gfn2/basis.hpp"
#include "model/gfn2/coordination.hpp"
#include "model/gfn2/eigensolver.hpp"
#include "model/gfn2/es2.hpp"
#include "model/gfn2/es3.hpp"
#include "model/gfn2/external_point_charges.hpp"
#include "model/gfn2/h0.hpp"
#include "model/gfn2/integrals.hpp"
#include "model/gfn2/mulliken.hpp"
#include "model/gfn2/scc_driver.hpp"
#include "model/gfn2/scc_mixer.hpp"
#include "model/gfn2/wavefunction.hpp"

#define CHECK(condition)                                                              \
  do {                                                                                \
    if (!(condition)) {                                                               \
      std::cerr << "CHECK failed at line " << __LINE__ << ": " << #condition << "\n"; \
      return 1;                                                                       \
    }                                                                                 \
  } while (false)

namespace {

using namespace gpuxtb::detail::gfn2;

constexpr double kKelvinToHartree = 3.166808578545117e-6;
// Match tblite's singlepoint convergence policy exactly: with accuracy=1.0
// the electronic energy gate is econv = 1.0e-6*accuracy and the population
// (density) gate is pconv = 2.0e-5*accuracy.  The goldens were generated by
// that pinned policy, so the closed-loop comparison is only meaningful when
// the CPU driver uses the same thresholds.
constexpr double kTbliteEnergyTolerance = 1.0e-6;
constexpr double kTbliteRmsTolerance = 2.0e-5;

struct AlignedBuffer {
  void* data = nullptr;
  std::size_t size = 0u;
  explicit AlignedBuffer(std::size_t requested) {
    size = (std::max<std::size_t>(requested, 1u) + 63u) & ~std::size_t{63u};
    data = std::aligned_alloc(64u, size);
    if (data != nullptr) {
      std::memset(data, 0, size);
    }
  }
  ~AlignedBuffer() { std::free(data); }
  AlignedBuffer(const AlignedBuffer&) = delete;
  AlignedBuffer& operator=(const AlignedBuffer&) = delete;
};

struct Geometry {
  std::int64_t batch_size = 1;
  std::vector<std::int64_t> atom_offsets{0, 0};
  std::vector<std::int32_t> atomic_numbers;
  std::vector<double> positions;
  std::vector<double> molecular_charges{0.0};
  std::vector<std::int32_t> unpaired{0};
  std::vector<std::int32_t> spins{1};

  BasisPlan basis;
  IntegralPlan integrals;
  H0Plan h0_plan;
  WavefunctionLayout layout;
  ES2Plan es2_plan;
  ES3Plan es3_plan;
  AES2Plan aes2_plan;
  MullikenPlan mulliken_plan;
  EigensolverPlan eig_plan;
  CoordinationPlan coordination_plan;

  std::vector<double> overlap, dint, qint, h0, cn;
  std::vector<std::int64_t> pc_offsets;
  std::vector<double> pc_positions, pc_charges, pc_hardnesses, pc_shell_potential;
  ExternalPointChargePlan pc_plan;

  AlignedBuffer iscratch{1u << 20}, e2s{1u << 21}, e2scratch{1u << 21}, a2s{1u << 21},
      a2scratch{1u << 21};
  ES2GeometryCache es2_cache;
  AES2GeometryCache aes2_cache;
  ES2Workspace es2_ws;
  AES2Workspace aes2_ws;

  AlignedBuffer wfn_s{1u << 21};
  WavefunctionView wfn;
  AlignedBuffer oc_s{1u << 21};
  EigensolverOverlapCache ocache;
  AlignedBuffer eig_s{1u << 21};
  EigensolverWorkspace eig_ws;
  CpuLinearAlgebraBackend backend;

  SccDriverGeometryView geom;

  gpuxtb_status_t build(std::string& err) {
    err.clear();
    const std::int64_t natoms = static_cast<std::int64_t>(atomic_numbers.size());
    atom_offsets = {0, natoms};
    gpuxtb_status_t s =
        make_basis_plan(batch_size, natoms, atom_offsets.data(), atomic_numbers.data(), basis, err);
    if (s) return s;
    s = make_integral_plan(basis, integrals, err);
    if (s) return s;
    s = make_h0_plan(basis, integrals, atomic_numbers.data(), h0_plan, err);
    if (s) return s;
    s = make_wavefunction_layout(basis, atomic_numbers.data(), molecular_charges.data(),
                                 unpaired.data(), spins.data(), layout, err);
    if (s) return s;
    s = make_es2_plan(basis, atomic_numbers.data(), es2_plan, err);
    if (s) return s;
    s = make_es3_plan(basis, atomic_numbers.data(), es3_plan, err);
    if (s) return s;
    s = make_aes2_plan(basis, atomic_numbers.data(), aes2_plan, err);
    if (s) return s;
    s = make_mulliken_plan(basis, integrals, layout, mulliken_plan, err);
    if (s) return s;
    s = make_eigensolver_plan(layout, eig_plan, err);
    if (s) return s;
    s = make_coordination_plan(batch_size, natoms, atom_offsets.data(), atomic_numbers.data(),
                               coordination_plan, err);
    if (s) return s;

    const std::size_t matrix = static_cast<std::size_t>(integrals.total_matrix_elements);
    overlap.assign(matrix, 0.0);
    dint.assign(3 * matrix, 0.0);
    qint.assign(6 * matrix, 0.0);
    h0.assign(matrix, 0.0);
    cn.assign(static_cast<std::size_t>(natoms), 0.0);
    if (iscratch.size < integrals.workspace_size_bytes) return GPUXTB_STATUS_ALLOCATION_FAILED;
    s = evaluate_coordination_cpu(coordination_plan, positions.data(), cn.data(), err);
    if (s) return s;
    s = evaluate_overlap_cpu(basis, integrals, positions.data(), overlap.data(), iscratch.data,
                             iscratch.size, err);
    if (s) return s;
    s = evaluate_multipole_cpu(basis, integrals, positions.data(), dint.data(), qint.data(),
                               iscratch.data, iscratch.size, err);
    if (s) return s;
    s = evaluate_h0_cpu(basis, integrals, h0_plan, positions.data(), cn.data(), overlap.data(),
                        h0.data(), err);
    if (s) return s;

    const std::size_t e2n = static_cast<std::size_t>(es2_plan.total_matrix_elements());
    if (e2s.size < e2n * sizeof(double)) return GPUXTB_STATUS_ALLOCATION_FAILED;
    es2_ws.matrix_scratch = static_cast<double*>(e2scratch.data);
    es2_ws.matrix_elements = es2_plan.total_matrix_elements();
    s = update_es2_geometry_cache_cpu(es2_plan, positions.data(), 1u,
                                      static_cast<double*>(e2s.data), e2n, es2_ws, es2_cache, err);
    if (s) return s;

    const std::size_t a2n = static_cast<std::size_t>(aes2_plan.pair_data_elements());
    if (a2s.size < a2n * sizeof(double)) return GPUXTB_STATUS_ALLOCATION_FAILED;
    aes2_ws.pair_scratch = static_cast<double*>(a2scratch.data);
    aes2_ws.pair_elements = aes2_plan.pair_data_elements();
    s = update_aes2_geometry_cache_cpu(aes2_plan, positions.data(), cn.data(), 1u,
                                       static_cast<double*>(a2s.data), a2n, aes2_ws, aes2_cache,
                                       err);
    if (s) return s;

    if (!pc_positions.empty()) {
      pc_offsets = {0, static_cast<std::int64_t>(pc_charges.size())};
      s = make_external_point_charge_plan(basis, atomic_numbers.data(),
                                          static_cast<std::int64_t>(pc_charges.size()),
                                          pc_offsets.data(), pc_plan, err);
      if (s) return s;
      pc_shell_potential.assign(static_cast<std::size_t>(basis.total_shells), 0.0);
      s = evaluate_external_point_charge_potential_cpu(
          pc_plan, positions.data(), pc_positions.data(), pc_charges.data(), pc_hardnesses.data(),
          pc_shell_potential.data(), err);
      if (s) return s;
    }

    geom.h0 = h0.data();
    geom.h0_elements = static_cast<std::int64_t>(h0.size());
    geom.integrals = {overlap.data(), dint.data(), qint.data(), integrals.total_matrix_elements,
                      mulliken_plan.identity()};
    geom.es2_cache = es2_cache;
    geom.aes2_cache = aes2_cache;
    geom.geometry_generation = 1u;
    if (!pc_positions.empty()) {
      geom.explicit_point_charge_shell_potential = pc_shell_potential.data();
      geom.explicit_point_charge_shell_elements =
          static_cast<std::int64_t>(pc_shell_potential.size());
    }

    s = make_mkl_rt_lp64_backend(backend, err);
    if (s) return s;
    if (wfn_s.size < layout.workspace_size_bytes) return GPUXTB_STATUS_ALLOCATION_FAILED;
    s = bind_wavefunction_view(layout, wfn_s.data, wfn_s.size, wfn, err);
    if (s) return s;
    s = initialize_sad_multipole_state(layout, wfn, err);
    if (s) return s;
    if (oc_s.size < eig_plan.overlap_cache_size_bytes()) return GPUXTB_STATUS_ALLOCATION_FAILED;
    s = bind_eigensolver_overlap_cache(eig_plan, oc_s.data, oc_s.size, ocache, err);
    if (s) return s;
    if (eig_s.size < eig_plan.workspace_size_bytes()) return GPUXTB_STATUS_ALLOCATION_FAILED;
    s = bind_eigensolver_workspace(eig_plan, eig_s.data, eig_s.size, eig_ws, err);
    if (s) return s;
    s = factor_overlap_cpu(eig_plan, overlap.data(), 1u, backend, eig_ws, ocache, err);
    if (s) return s;
    return GPUXTB_STATUS_SUCCESS;
  }
};

struct Stage {
  SccMixerPlan mixer_plan;
  SccDriverPlan driver_plan;
  AlignedBuffer mixer_s{1u << 21};
  SccMixerState mixer_state;
  AlignedBuffer drv_s{1u << 21};
  SccDriverState driver_state;
  AlignedBuffer drvws_s{1u << 21};
  SccDriverWorkspace drv_ws;

  gpuxtb_status_t build(Geometry& g, std::int64_t history, double damping, double rms_tol,
                        double e_tol, std::uint64_t max_iter, double etemp, std::string& err) {
    err.clear();
    gpuxtb_status_t s =
        make_scc_mixer_plan(g.layout, history, damping, rms_tol, rms_tol, mixer_plan, err);
    if (s) return s;
    s = make_scc_driver_plan(g.layout, g.mulliken_plan, g.es2_plan, g.es3_plan, g.aes2_plan,
                             g.eig_plan, mixer_plan, nullptr, nullptr, max_iter, etemp, e_tol,
                             driver_plan, err);
    if (s) return s;
    if (mixer_s.size < mixer_plan.state_size_bytes()) return GPUXTB_STATUS_ALLOCATION_FAILED;
    s = bind_scc_mixer_state(mixer_plan, mixer_s.data, mixer_s.size, mixer_state, err);
    if (s) return s;
    if (drv_s.size < driver_plan.state_size_bytes()) return GPUXTB_STATUS_ALLOCATION_FAILED;
    s = bind_scc_driver_state(driver_plan, drv_s.data, drv_s.size, driver_state, err);
    if (s) return s;
    if (drvws_s.size < driver_plan.workspace_size_bytes()) return GPUXTB_STATUS_ALLOCATION_FAILED;
    s = bind_scc_driver_workspace(driver_plan, drvws_s.data, drvws_s.size, drv_ws, err);
    if (s) return s;
    s = initialize_scc_driver_state_cpu(driver_plan, g.wfn, mixer_state, driver_state, err);
    return s;
  }
};

struct CaseSpec {
  std::int64_t nat = 0;
  std::vector<std::int32_t> atomic_numbers;
  std::vector<double> positions;
  double molecular_charge = 0.0;
  std::int32_t unpaired_electrons = 0;
  double temperature_kelvin = 300.0;
  std::int64_t mixer_memory = 2;
  double mixer_damping = 0.4;
  std::int64_t maximum_iterations = 100;
  std::vector<double> pc_rows;  // x y z q gamma per point charge
};

bool load_spec(const std::string& path, CaseSpec& spec, std::string& err) {
  std::ifstream file(path);
  if (!file) {
    err = "cannot open spec " + path;
    return false;
  }
  if (!(file >> spec.nat)) {
    err = "missing atom count";
    return false;
  }
  spec.atomic_numbers.resize(static_cast<std::size_t>(spec.nat));
  for (auto& number : spec.atomic_numbers) {
    if (!(file >> number)) {
      err = "missing atomic number";
      return false;
    }
  }
  spec.positions.resize(static_cast<std::size_t>(spec.nat * 3));
  for (auto& value : spec.positions) {
    if (!(file >> value)) {
      err = "missing position";
      return false;
    }
  }
  if (!(file >> spec.molecular_charge)) {
    err = "missing charge";
    return false;
  }
  if (!(file >> spec.unpaired_electrons)) {
    err = "missing unpaired electrons";
    return false;
  }
  if (!(file >> spec.temperature_kelvin)) {
    err = "missing temperature";
    return false;
  }
  if (!(file >> spec.mixer_memory)) {
    err = "missing mixer memory";
    return false;
  }
  if (!(file >> spec.mixer_damping)) {
    err = "missing mixer damping";
    return false;
  }
  if (!(file >> spec.maximum_iterations)) {
    err = "missing max iterations";
    return false;
  }
  std::int64_t npc = 0;
  if (!(file >> npc)) {
    err = "missing point-charge count";
    return false;
  }
  spec.pc_rows.resize(static_cast<std::size_t>(npc * 5));
  for (auto& value : spec.pc_rows) {
    if (!(file >> value)) {
      err = "missing point-charge value";
      return false;
    }
  }
  return true;
}

void emit_value(double value) {
  std::cout << std::setprecision(17) << std::scientific << value << "\n";
}
void emit_int(std::int64_t value) { std::cout << value << "\n"; }

// One captured iteration in the raw stream section order.
struct CapturedIteration {
  std::vector<double> hamiltonian, eigenvalues, occupations_alpha, occupations_beta, density;
  std::vector<double> mixed_qsh, mixed_qat, mixed_dipoles, mixed_quadrupoles;
  std::vector<double> raw_qsh, raw_qat, raw_dipoles, raw_quadrupoles;
  std::vector<double> point_charge_shell_potential, point_charge_energy;
  double energy = 0.0;
  double energy_delta = 0.0;
  double residual_rms = 0.0;
  int econv = 0;
  int pconv = 0;
  int tconv = 1;
  int conv = 0;
};

int capture_case(const std::string& spec_path) {
  CaseSpec spec;
  std::string err;
  if (!load_spec(spec_path, spec, err)) {
    std::cerr << err << "\n";
    return 2;
  }

  Geometry geometry;
  geometry.atomic_numbers = spec.atomic_numbers;
  geometry.positions = spec.positions;
  geometry.molecular_charges = {spec.molecular_charge};
  geometry.unpaired = {spec.unpaired_electrons};
  const std::int64_t npc = static_cast<std::int64_t>(spec.pc_rows.size() / 5);
  for (std::int64_t ip = 0; ip < npc; ++ip) {
    const double* row = &spec.pc_rows[static_cast<std::size_t>(ip * 5)];
    geometry.pc_positions.insert(geometry.pc_positions.end(), {row[0], row[1], row[2]});
    geometry.pc_charges.push_back(row[3]);
    geometry.pc_hardnesses.push_back(row[4]);
  }
  if (gpuxtb_status_t s = geometry.build(err); s != GPUXTB_STATUS_SUCCESS) {
    std::cerr << "geometry build failed: " << err << "\n";
    return static_cast<int>(s);
  }

  Stage stage;
  if (gpuxtb_status_t s =
          stage.build(geometry, spec.mixer_memory, spec.mixer_damping, kTbliteRmsTolerance,
                      kTbliteEnergyTolerance, static_cast<std::uint64_t>(spec.maximum_iterations),
                      spec.temperature_kelvin * kKelvinToHartree, err);
      s != GPUXTB_STATUS_SUCCESS) {
    std::cerr << "stage build failed: " << err << "\n";
    return static_cast<int>(s);
  }

  const std::int64_t nat = spec.nat;
  const std::int64_t nsh = geometry.basis.total_shells;
  const std::int64_t nao = geometry.layout.total_orbitals;
  const std::int64_t system = 0;
  const std::int64_t matrix_elements =
      static_cast<std::int64_t>(geometry.layout.density.system_offsets[system + 1] -
                                geometry.layout.density.system_offsets[system]);

  std::vector<CapturedIteration> iterations;

  for (std::uint64_t it = 0; it < static_cast<std::uint64_t>(spec.maximum_iterations); ++it) {
    CapturedIteration row;
    const std::int64_t shell_begin = geometry.basis.batch_shell_offsets[system];
    const std::int64_t shell_end = geometry.basis.batch_shell_offsets[system + 1];
    const std::int64_t nsh_local = shell_end - shell_begin;
    CHECK(nsh_local == nsh);

    // Mixed q/d/Q are the pre-solve wavefunction state.
    row.mixed_qsh.assign(geometry.wfn.qsh + shell_begin, geometry.wfn.qsh + shell_end);
    const std::int64_t qat_begin = geometry.layout.qat.system_offsets[system];
    const std::int64_t qat_end = geometry.layout.qat.system_offsets[system + 1];
    row.mixed_qat.assign(geometry.wfn.qat + qat_begin, geometry.wfn.qat + qat_end);
    const std::int64_t dip_begin = geometry.layout.dipole.system_offsets[system];
    const std::int64_t dip_end = geometry.layout.dipole.system_offsets[system + 1];
    row.mixed_dipoles.assign(geometry.wfn.dipole + dip_begin, geometry.wfn.dipole + dip_end);
    const std::int64_t quad_begin = geometry.layout.quadrupole.system_offsets[system];
    const std::int64_t quad_end = geometry.layout.quadrupole.system_offsets[system + 1];
    row.mixed_quadrupoles.assign(geometry.wfn.quadrupole + quad_begin,
                                 geometry.wfn.quadrupole + quad_end);

    const gpuxtb_status_t s = iterate_scc_driver_batch_cpu(
        stage.driver_plan, geometry.geom, geometry.backend, geometry.ocache, geometry.wfn,
        stage.mixer_state, stage.driver_state, stage.drv_ws, err);
    if (s != GPUXTB_STATUS_SUCCESS && s != GPUXTB_STATUS_SCC_NOT_CONVERGED) {
      std::cerr << "driver iteration failed: " << err << "\n";
      return static_cast<int>(s);
    }

    const std::int64_t density_base = geometry.layout.density.system_offsets[system];
    row.hamiltonian.assign(stage.drv_ws.hamiltonian + density_base,
                           stage.drv_ws.hamiltonian + density_base + matrix_elements);
    row.density.assign(stage.drv_ws.staged_wavefunction.density + density_base,
                       stage.drv_ws.staged_wavefunction.density + density_base + matrix_elements);
    const std::int64_t eig_begin = geometry.layout.eigenvalues.system_offsets[system];
    row.eigenvalues.assign(stage.drv_ws.staged_wavefunction.eigenvalues + eig_begin,
                           stage.drv_ws.staged_wavefunction.eigenvalues + eig_begin + nao);
    const std::int64_t occ_begin = geometry.layout.occupations.system_offsets[system];
    row.occupations_alpha.assign(stage.drv_ws.staged_wavefunction.occupations + occ_begin,
                                 stage.drv_ws.staged_wavefunction.occupations + occ_begin + nao);
    // Restricted: both channels share the same orbital occupations.
    row.occupations_beta = row.occupations_alpha;

    row.raw_qsh.assign(stage.drv_ws.raw_qsh + shell_begin, stage.drv_ws.raw_qsh + shell_end);
    row.raw_qat.assign(stage.drv_ws.raw_qat + qat_begin, stage.drv_ws.raw_qat + qat_end);
    row.raw_dipoles.assign(stage.drv_ws.raw_dipoles + dip_begin,
                           stage.drv_ws.raw_dipoles + dip_end);
    row.raw_quadrupoles.assign(stage.drv_ws.raw_quadrupoles + quad_begin,
                               stage.drv_ws.raw_quadrupoles + quad_end);

    if (!geometry.pc_shell_potential.empty()) {
      row.point_charge_shell_potential = geometry.pc_shell_potential;
      row.point_charge_energy.resize(static_cast<std::size_t>(nsh));
      for (std::int64_t sh = 0; sh < nsh; ++sh) {
        row.point_charge_energy[static_cast<std::size_t>(sh)] =
            row.raw_qsh[static_cast<std::size_t>(sh)] *
            geometry.pc_shell_potential[static_cast<std::size_t>(sh)];
      }
    }

    row.energy = stage.driver_state.internal_energies[system];
    row.energy_delta = stage.driver_state.free_energy_changes[system];
    row.residual_rms = stage.drv_ws.staged_mixer_state.residual_rms[system];
    row.econv = std::abs(row.energy_delta) < stage.driver_plan.energy_tolerance() ? 1 : 0;
    row.pconv = row.residual_rms < stage.mixer_plan.rms_tolerance() ? 1 : 0;
    row.conv = stage.driver_state.converged[system] ? 1 : 0;
    CHECK(row.conv == (row.econv && row.pconv && row.tconv));
    iterations.push_back(std::move(row));

    if (stage.driver_state.converged[system] != 0) {
      break;
    }
    if (stage.driver_state.system_statuses[system] != GPUXTB_STATUS_SUCCESS &&
        stage.driver_state.system_statuses[system] != GPUXTB_STATUS_SCC_NOT_CONVERGED) {
      break;
    }
  }

  const std::int64_t niterations = static_cast<std::int64_t>(iterations.size());
  const std::int64_t terminal = (niterations > 0 && iterations.back().conv) ? 1 : 2;

  std::cout << "nat " << nat << " nsh " << nsh << " nao " << nao << " niterations " << niterations
            << " terminal " << terminal << "\n";
  std::cout << "atomic_numbers\n";
  for (std::int64_t i = 0; i < nat; ++i) emit_int(spec.atomic_numbers[static_cast<std::size_t>(i)]);
  std::cout << "positions\n";
  for (double v : geometry.positions) emit_value(v);
  std::cout << "molecular_charge\n";
  emit_value(spec.molecular_charge);
  std::cout << "unpaired_electrons\n";
  emit_int(spec.unpaired_electrons);
  std::cout << "temperature\n";
  emit_value(spec.temperature_kelvin);
  std::cout << "n_point_charges\n";
  emit_int(npc);
  for (std::int64_t ip = 0; ip < npc; ++ip) {
    const double* row = &spec.pc_rows[static_cast<std::size_t>(ip * 5)];
    for (std::int64_t j = 0; j < 5; ++j) emit_value(row[j]);
  }
  std::cout << "atom_to_shell_count\n";
  for (std::int64_t i = 0; i < nat; ++i) {
    const std::int64_t begin = geometry.basis.atom_shell_offsets[i];
    const std::int64_t end = geometry.basis.atom_shell_offsets[i + 1];
    emit_int(end - begin);
  }

  std::cout << "overlap\n";
  for (std::int64_t col = 0; col < nao; ++col)
    for (std::int64_t row = 0; row < nao; ++row)
      emit_value(geometry.overlap[static_cast<std::size_t>(col * nao + row)]);
  std::cout << "core_hamiltonian\n";
  for (std::int64_t col = 0; col < nao; ++col)
    for (std::int64_t row = 0; row < nao; ++row)
      emit_value(geometry.h0[static_cast<std::size_t>(col * nao + row)]);

  for (std::int64_t i = 0; i < niterations; ++i) {
    const CapturedIteration& row = iterations[static_cast<std::size_t>(i)];
    std::cout << "iteration\n";
    emit_int(i + 1);
    std::cout << "hamiltonian\n";
    for (std::int64_t col = 0; col < nao; ++col)
      for (std::int64_t r = 0; r < nao; ++r)
        emit_value(row.hamiltonian[static_cast<std::size_t>(col * nao + r)]);
    std::cout << "eigenvalues\n";
    for (double v : row.eigenvalues) emit_value(v);
    std::cout << "occupations\n";
    for (double v : row.occupations_alpha) emit_value(v);
    for (double v : row.occupations_beta) emit_value(v);
    std::cout << "density\n";
    for (std::int64_t col = 0; col < nao; ++col)
      for (std::int64_t r = 0; r < nao; ++r)
        emit_value(row.density[static_cast<std::size_t>(col * nao + r)]);
    std::cout << "mixed_qsh\n";
    for (double v : row.mixed_qsh) emit_value(v);
    std::cout << "mixed_qat\n";
    for (double v : row.mixed_qat) emit_value(v);
    std::cout << "mixed_dipoles\n";
    for (double v : row.mixed_dipoles) emit_value(v);
    std::cout << "mixed_quadrupoles\n";
    for (double v : row.mixed_quadrupoles) emit_value(v);
    std::cout << "raw_qsh\n";
    for (double v : row.raw_qsh) emit_value(v);
    std::cout << "raw_qat\n";
    for (double v : row.raw_qat) emit_value(v);
    std::cout << "raw_dipoles\n";
    for (double v : row.raw_dipoles) emit_value(v);
    std::cout << "raw_quadrupoles\n";
    for (double v : row.raw_quadrupoles) emit_value(v);
    if (npc > 0) {
      std::cout << "point_charge_shell_potential\n";
      for (double v : row.point_charge_shell_potential) emit_value(v);
      std::cout << "point_charge_energy\n";
      for (double v : row.point_charge_energy) emit_value(v);
    }
    std::cout << "energy\n";
    emit_value(row.energy);
    std::cout << "energy_delta\n";
    emit_value(row.energy_delta);
    std::cout << "residual_rms\n";
    emit_value(row.residual_rms);
    std::cout << "convergence\n";
    emit_int(row.econv);
    emit_int(row.pconv);
    emit_int(row.tconv);
    emit_int(row.conv);
  }
  return 0;
}

}  // namespace

int main(int argc, char** argv) {
  if (argc != 2) {
    std::cerr << "usage: gpuxtb_scc_trace_capture <case.spec>\n";
    return 64;
  }
  return capture_case(argv[1]);
}
