#!/usr/bin/env python3
"""Validate or refresh the difficult-SCC fixture and generated evidence manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
EVIDENCE_DIRECTORY_RELATIVE = Path(
    "data/conformance/evidence/tmacl-temperature-continuation"
)
EVIDENCE_DIRECTORY = REPOSITORY_ROOT / EVIDENCE_DIRECTORY_RELATIVE
FIXTURE_RELATIVE = Path("data/conformance/inputs/tmacl.xyz")
GENERATOR_RELATIVE = Path("tests/scc_temperature_continuation_test.cpp")
DEFAULT_MANIFEST = EVIDENCE_DIRECTORY / "manifest.json"
EXPECTED_EVIDENCE = (
    "tmacl_continuation_funnel.txt",
    "tmacl_mixer_sweep.txt",
    "tmacl_path_sensitivity.txt",
    "tmacl_trace_300K.txt",
    "tmacl_trace_400K.txt",
    "tmacl_trace_450K.txt",
    "tmacl_trace_500K.txt",
    "tmacl_trace_1000K.txt",
)
SHA256_PATTERN = re.compile(r"[0-9a-f]{64}")
COMMIT_PATTERN = re.compile(r"[0-9a-f]{40}")


class EvidenceError(ValueError):
    """Report malformed provenance or content drift."""


def sha256(path: Path) -> str:
    """Return the SHA-256 digest of one file without normalizing its bytes."""
    digest = hashlib.sha256()
    try:
        with path.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(chunk)
    except OSError as exc:
        raise EvidenceError(f"cannot read pinned file {path}: {exc}") from exc
    return digest.hexdigest()


def repository_path(value: object, field: str) -> Path:
    """Resolve one manifest path while rejecting traversal outside the repository."""
    if not isinstance(value, str) or not value:
        raise EvidenceError(f"{field} must be a nonempty repository-relative path")
    relative = Path(value)
    if relative.is_absolute():
        raise EvidenceError(f"{field} must be a repository-relative path")
    candidate = (REPOSITORY_ROOT / relative).resolve()
    try:
        candidate.relative_to(REPOSITORY_ROOT)
    except ValueError as exc:
        raise EvidenceError(f"{field} escapes the repository") from exc
    return candidate


def require_sha256(value: object, field: str) -> str:
    """Validate a lowercase SHA-256 string."""
    if not isinstance(value, str) or SHA256_PATTERN.fullmatch(value) is None:
        raise EvidenceError(f"{field} must be a lowercase SHA-256 digest")
    return value


def require_commit(value: object, field: str) -> str:
    """Validate a full lowercase Git object identifier without requiring .git."""
    if not isinstance(value, str) or COMMIT_PATTERN.fullmatch(value) is None:
        raise EvidenceError(f"{field} must be a full lowercase commit identifier")
    return value


def require_exact_path(value: object, expected: Path, field: str) -> Path:
    """Require the reviewed canonical spelling as well as repository containment."""
    canonical = expected.as_posix()
    if value != canonical:
        raise EvidenceError(f"{field} must be the canonical path {canonical}")
    return repository_path(value, field)


def validate_xyz(path: Path) -> None:
    """Reject truncated, non-finite, or extended copies of the 18-atom fixture."""
    lines = path.read_text(encoding="ascii").splitlines()
    if len(lines) != 20 or lines[0] != "18" or lines[1] != "tmacl":
        raise EvidenceError("tmacl fixture must contain its exact 18-row XYZ envelope")
    allowed = {"C", "H", "N", "Cl"}
    for atom, line in enumerate(lines[2:], start=1):
        fields = line.split()
        if len(fields) != 4 or fields[0] not in allowed:
            raise EvidenceError(f"tmacl fixture atom row {atom} is malformed")
        try:
            coordinates = [float(value) for value in fields[1:]]
        except ValueError as exc:
            raise EvidenceError(
                f"tmacl fixture atom row {atom} has a non-numeric coordinate"
            ) from exc
        if not all(math.isfinite(value) for value in coordinates):
            raise EvidenceError(
                f"tmacl fixture atom row {atom} has a non-finite coordinate"
            )


def load_manifest(path: Path) -> dict[str, object]:
    """Load one manifest object with a stable diagnostic for malformed JSON."""
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise EvidenceError(f"cannot load evidence manifest {path}: {exc}") from exc
    if not isinstance(manifest, dict):
        raise EvidenceError("evidence manifest root must be an object")
    return manifest


def check_manifest(path: Path = DEFAULT_MANIFEST) -> None:
    """Validate provenance fields and every pinned source/generated byte."""
    manifest = load_manifest(path)
    if manifest.get("schema_version") != 1:
        raise EvidenceError("evidence manifest schema_version must be 1")

    fixture = manifest.get("fixture")
    if not isinstance(fixture, dict):
        raise EvidenceError("evidence manifest fixture must be an object")
    fixture_path = require_exact_path(
        fixture.get("path"), FIXTURE_RELATIVE, "fixture.path"
    )
    validate_xyz(fixture_path)
    expected_fixture = require_sha256(fixture.get("sha256"), "fixture.sha256")
    if sha256(fixture_path) != expected_fixture:
        raise EvidenceError("tmacl fixture SHA-256 does not match the manifest")
    source = fixture.get("source")
    if not isinstance(source, dict):
        raise EvidenceError("fixture.source must be an object")
    if source.get("url") != "https://github.com/grimme-lab/xtb/issues/678":
        raise EvidenceError("fixture.source.url must identify upstream xTB issue #678")
    if source.get("issue_node_id") != "I_kwDODKCtwM5PRfQc":
        raise EvidenceError(
            "fixture.source.issue_node_id is not the pinned upstream issue"
        )
    expected_source_metadata = {
        "author": "corinwagen",
        "created_at": "2022-08-05T14:04:47Z",
        "retrieved_at": "2026-08-07",
        "extraction": "Verbatim 18-atom XYZ fenced block from the public issue body.",
    }
    for field, expected in expected_source_metadata.items():
        if source.get(field) != expected:
            raise EvidenceError(f"fixture.source.{field} is not the reviewed value")
    if source.get("excerpt_sha256") != expected_fixture:
        raise EvidenceError(
            "fixture source excerpt digest must equal the verbatim XYZ digest"
        )
    licensing = source.get("licensing")
    if not isinstance(licensing, dict) or licensing.get("spdx") != "NOASSERTION":
        raise EvidenceError(
            "fixture source must retain its explicit NOASSERTION assessment"
        )
    if not isinstance(licensing.get("assessment"), str) or not licensing["assessment"]:
        raise EvidenceError("fixture licensing assessment must be documented")

    generator = manifest.get("generator")
    if not isinstance(generator, dict):
        raise EvidenceError("evidence manifest generator must be an object")
    source_path = require_exact_path(
        generator.get("source"), GENERATOR_RELATIVE, "generator.source"
    )
    expected_source = require_sha256(
        generator.get("source_sha256"), "generator.source_sha256"
    )
    if sha256(source_path) != expected_source:
        raise EvidenceError("evidence generator SHA-256 does not match the manifest")
    if generator.get("command") != (
        "gpuxtb_scc_temperature_continuation_test --write-evidence "
        "data/conformance/evidence/tmacl-temperature-continuation"
    ):
        raise EvidenceError("evidence generator command is not canonical")
    expected_generator_metadata = {
        "physics_baseline_commit": "9fd7d4ddce3d5cb576b5bce8005a1f90647d37c0",
        "refresh_base_commit": "66ae5e7b7fb622d263f2f94974ffbb9f2e3b7d23",
        "generated_at": "2026-08-07",
    }
    for field, expected in expected_generator_metadata.items():
        if field.endswith("commit"):
            require_commit(generator.get(field), f"generator.{field}")
        if generator.get(field) != expected:
            raise EvidenceError(f"generator.{field} is not the reviewed value")
    expected_runtime = {
        "provider": "Intel oneAPI Math Kernel Library",
        "version": "2026.1.0",
        "interface": "LP64",
        "threading": "sequential",
        "library_sha256": (
            "b2ff0e31d7cd18c91813d8f6500f37665597d89de22649d90687aa6bf7bd2c0f"
        ),
    }
    runtime = generator.get("runtime")
    if not isinstance(runtime, dict):
        raise EvidenceError("generator.runtime must be an object")
    for field, expected in expected_runtime.items():
        if runtime.get(field) != expected:
            raise EvidenceError(f"generator.runtime.{field} is not the reviewed value")
    require_sha256(runtime.get("library_sha256"), "generator.runtime.library_sha256")

    semantic_cross_check = manifest.get("semantic_cross_check")
    expected_cross_check = {
        "provider": "scipy-openblas32",
        "version": "0.3.34.0.0",
        "interface": "LP64 with scipy_ symbol prefix",
        "library_sha256": (
            "b2dfe24b9aa11cf1d1cec8edbca9423b50cfd186b486d59dd4efe45826261a98"
        ),
        "required_result": (
            "The executable assertion matrix, including exact baseline iteration "
            "counts and final q/d/Q plus density comparisons, passes unchanged."
        ),
    }
    if not isinstance(semantic_cross_check, dict):
        raise EvidenceError("semantic_cross_check must be an object")
    for field, expected in expected_cross_check.items():
        if semantic_cross_check.get(field) != expected:
            raise EvidenceError(
                f"semantic_cross_check.{field} is not the reviewed value"
            )
    require_sha256(
        semantic_cross_check.get("library_sha256"),
        "semantic_cross_check.library_sha256",
    )

    distribution = manifest.get("distribution")
    expected_distribution = {
        "classification": "copied test fixture and gpuxtb-generated test diagnostics",
        "source_distribution": True,
        "native_install": False,
        "wheel": False,
        "notice": "THIRD_PARTY_NOTICES.md",
    }
    if distribution != expected_distribution:
        raise EvidenceError("distribution boundaries or notice path are not canonical")
    notice_path = repository_path(distribution["notice"], "distribution.notice")
    try:
        notice = notice_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise EvidenceError(f"cannot read tmacl third-party notice: {exc}") from exc
    required_notice_text = (
        "## xTB issue #678 difficult-SCC input",
        "https://github.com/grimme-lab/xtb/issues/678",
        "SPDX: NOASSERTION",
        "included in source distributions",
        "data/conformance/evidence/tmacl-temperature-continuation/manifest.json",
    )
    if any(value not in notice for value in required_notice_text):
        raise EvidenceError(
            "tmacl third-party notice is missing required provenance text"
        )

    files = manifest.get("evidence_files")
    if not isinstance(files, list):
        raise EvidenceError("evidence_files must be an array")
    recorded: dict[str, str] = {}
    canonical_evidence_paths = {
        (EVIDENCE_DIRECTORY_RELATIVE / name).as_posix(): name
        for name in EXPECTED_EVIDENCE
    }
    for index, entry in enumerate(files):
        if not isinstance(entry, dict):
            raise EvidenceError(f"evidence_files[{index}] must be an object")
        path_value = entry.get("path")
        if (
            not isinstance(path_value, str)
            or path_value not in canonical_evidence_paths
        ):
            raise EvidenceError(
                f"evidence_files[{index}].path is not a canonical evidence path"
            )
        evidence_path = repository_path(path_value, f"evidence_files[{index}].path")
        name = canonical_evidence_paths[path_value]
        if name in recorded:
            raise EvidenceError(f"duplicate evidence file {name}")
        recorded[name] = require_sha256(
            entry.get("sha256"), f"evidence_files[{index}].sha256"
        )
        if sha256(evidence_path) != recorded[name]:
            raise EvidenceError(f"evidence file SHA-256 mismatch: {name}")
    if tuple(sorted(recorded)) != tuple(sorted(EXPECTED_EVIDENCE)):
        raise EvidenceError(
            "manifest must pin the complete expected tmacl evidence set"
        )

    on_disk = tuple(
        sorted(item.name for item in EVIDENCE_DIRECTORY.glob("tmacl_*.txt"))
    )
    if on_disk != tuple(sorted(EXPECTED_EVIDENCE)):
        raise EvidenceError(
            "evidence directory contains an unmanifested or missing tmacl file"
        )


def update_manifest(path: Path = DEFAULT_MANIFEST) -> None:
    """Refresh only local content digests after intentional regeneration."""
    manifest = load_manifest(path)
    fixture = manifest["fixture"]
    generator = manifest["generator"]
    assert isinstance(fixture, dict) and isinstance(generator, dict)
    fixture_path = repository_path(fixture["path"], "fixture.path")
    validate_xyz(fixture_path)
    fixture_digest = sha256(fixture_path)
    fixture["sha256"] = fixture_digest
    source = fixture["source"]
    assert isinstance(source, dict)
    source["excerpt_sha256"] = fixture_digest
    generator_path = repository_path(generator["source"], "generator.source")
    generator["source_sha256"] = sha256(generator_path)
    manifest["evidence_files"] = [
        {
            "path": (EVIDENCE_DIRECTORY_RELATIVE / name).as_posix(),
            "sha256": sha256(EVIDENCE_DIRECTORY / name),
        }
        for name in EXPECTED_EVIDENCE
    ]
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    check_manifest(path)


def main() -> int:
    """Run the check-only default or an explicit digest refresh."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument(
        "--update",
        action="store_true",
        help="refresh hashes after reviewed regeneration",
    )
    arguments = parser.parse_args()
    try:
        if arguments.update:
            update_manifest(arguments.manifest.resolve())
        else:
            check_manifest(arguments.manifest.resolve())
    except EvidenceError as exc:
        parser.exit(1, f"FAIL tmacl evidence: {exc}\n")
    print(  # noqa: T201 - CLI success output is part of the checker contract.
        f"PASS tmacl evidence: {len(EXPECTED_EVIDENCE)} generated files"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
