"""Offline validation for the canonical GFN1-xTB parameter bundle."""

from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

import tomllib

REPOSITORY = Path(__file__).resolve().parents[2]
DATA_DIR = REPOSITORY / "data" / "parameters"
GENERATOR_PATH = REPOSITORY / "tools" / "parameters" / "generate_gfn1.py"
SPEC = importlib.util.spec_from_file_location("xtbloom_generate_gfn1", GENERATOR_PATH)
assert SPEC is not None and SPEC.loader is not None
GENERATOR = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(GENERATOR)


class Gfn1ParameterTests(unittest.TestCase):
    """Verify GFN1-specific model tables, provenance, and generated bytes."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.raw_bytes = (DATA_DIR / GENERATOR.RAW_FILENAME).read_bytes()
        cls.raw = tomllib.loads(cls.raw_bytes.decode("utf-8"))
        cls.normalized = json.loads(
            (DATA_DIR / GENERATOR.JSON_FILENAME).read_text(encoding="utf-8")
        )
        cls.manifest = json.loads(
            (DATA_DIR / GENERATOR.MANIFEST_FILENAME).read_text(encoding="utf-8")
        )

    def test_complete_export_round_trips(self) -> None:
        self.assertEqual(GENERATOR.normalize_export(self.raw), self.normalized)
        self.assertEqual(self.normalized["method"], "gfn1-xtb")
        self.assertEqual(len(self.normalized["elements"]), 86)
        self.assertEqual(
            sum(len(element["shells"]) for element in self.normalized["elements"]),
            237,
        )

    def test_gfn1_specific_global_models_are_explicit(self) -> None:
        self.assertEqual(self.normalized["dispersion"]["model"], "d3")
        self.assertFalse(self.normalized["dispersion"]["self_consistent"])
        self.assertEqual(self.normalized["hamiltonian"]["coordination_number"], "exp")
        self.assertEqual(self.normalized["charge"]["average"], "harmonic")
        self.assertEqual(self.normalized["thirdorder"]["mode"], "atom")
        self.assertFalse(self.normalized["thirdorder"]["shell_resolved"])
        self.assertEqual(
            self.normalized["halogen"], {"damping": 0.44, "radius_scale": 1.3}
        )

    def test_atomwise_third_order_and_halogen_strengths_survive(self) -> None:
        by_symbol = {
            element["symbol"]: element for element in self.normalized["elements"]
        }
        self.assertEqual(by_symbol["He"]["gam3"], 0.15)
        self.assertEqual(by_symbol["F"]["gam3"], 0.1615037)
        self.assertEqual(by_symbol["Cl"]["xbond"], 0.0)
        self.assertEqual(by_symbol["Br"]["xbond"], 0.0381742)
        self.assertEqual(by_symbol["I"]["xbond"], 0.0321944)
        self.assertEqual(by_symbol["At"]["xbond"], 0.022)

    def test_pair_override_table_is_complete_and_symmetric(self) -> None:
        overrides = self.normalized["hamiltonian"]["pair_scale_overrides"]
        self.assertEqual(len(overrides), 869)
        table = {tuple(entry["atomic_numbers"]): entry["value"] for entry in overrides}
        self.assertEqual(table[(1, 1)], 0.96)
        self.assertEqual(table[(1, 5)], 0.95)
        self.assertEqual(table[(1, 28)], 0.9)
        self.assertEqual(table[(1, 75)], 0.8)
        self.assertEqual(table[(21, 39)], 1.15)
        self.assertEqual(table[(39, 39)], 1.2)
        self.assertEqual(self.normalized["hamiltonian"]["pair_scale_default"], 1.0)

    def test_repeated_angular_momentum_shell_marks_only_first_valence(self) -> None:
        hydrogen = self.normalized["elements"][0]
        self.assertEqual(
            [shell["principal_quantum_number"] for shell in hydrogen["shells"]], [1, 2]
        )
        self.assertEqual(
            [shell["angular_momentum"] for shell in hydrogen["shells"]], [0, 0]
        )
        self.assertEqual(
            [shell["is_valence"] for shell in hydrogen["shells"]], [True, False]
        )
        self.assertEqual(
            [shell["reference_occupation"] for shell in hydrogen["shells"]], [1.0, 0.0]
        )

    def test_repeated_shell_with_nonzero_occupation_is_rejected(self) -> None:
        invalid = copy.deepcopy(self.raw)
        invalid["element"]["H"]["refocc"][1] = 1.0
        with self.assertRaisesRegex(GENERATOR.ParameterError, "must have zero refocc"):
            GENERATOR.normalize_export(invalid)

    def test_wrong_gfn1_algorithm_selectors_are_rejected(self) -> None:
        for path, value, message in (
            (("hamiltonian", "xtb", "cn"), "dexp", "coordination-number"),
            (("charge", "effective", "average"), "arithmetic", "charge average"),
            (("thirdorder", "shell"), True, "atomwise"),
        ):
            invalid = copy.deepcopy(self.raw)
            target = invalid
            for key in path[:-1]:
                target = target[key]
            target[path[-1]] = value
            with self.assertRaisesRegex(GENERATOR.ParameterError, message):
                GENERATOR.normalize_export(invalid)

    def test_manifest_pins_release_source_and_diagnostic_cross_check(self) -> None:
        self.assertEqual(
            self.manifest["source"]["revision"],
            "fa8a4416e8fe093d0075bc10ac875494c2a449a9",
        )
        self.assertEqual(
            self.manifest["inspection"]["revision"],
            "133f91efb94b47f05848e1f86832f40a1accc385",
        )
        self.assertIn(
            "formatting/style only",
            self.manifest["inspection"]["reviewed_classification"],
        )
        cross_check = self.manifest["cross_check"]
        self.assertEqual(cross_check["role"], "non-authoritative semantic cross-check")
        self.assertEqual(cross_check["maximum_ulp_difference"], 2)
        self.assertEqual(cross_check["differing_binary64_values"], 157)
        for filename, metadata in self.manifest["outputs"].items():
            content = (DATA_DIR / filename).read_bytes()
            self.assertEqual(len(content), metadata["bytes"])
            self.assertEqual(hashlib.sha256(content).hexdigest(), metadata["sha256"])

    def test_offline_regeneration_is_byte_deterministic(self) -> None:
        provenance = {
            key: self.manifest[key]
            for key in ("source", "inspection", "exporter", "cross_check")
        }
        generated = GENERATOR.build_artifacts(self.raw_bytes, provenance)
        for filename, content in generated.items():
            self.assertEqual(content, (DATA_DIR / filename).read_bytes(), filename)

    def test_stale_generated_file_is_rejected(self) -> None:
        provenance = {
            key: self.manifest[key]
            for key in ("source", "inspection", "exporter", "cross_check")
        }
        generated = GENERATOR.build_artifacts(self.raw_bytes, provenance)
        with tempfile.TemporaryDirectory(prefix="xtbloom-gfn1-stale-") as directory:
            output = Path(directory)
            GENERATOR.write_or_check(output, generated, check=False)
            (output / GENERATOR.HEADER_FILENAME).write_bytes(b"stale\n")
            with self.assertRaisesRegex(GENERATOR.ParameterError, "gfn1.hpp"):
                GENERATOR.write_or_check(output, generated, check=True)

    def test_generated_header_compiles(self) -> None:
        compiler = shutil.which("c++")
        if compiler is None:
            self.skipTest("C++ compiler is unavailable")
        with tempfile.TemporaryDirectory(prefix="xtbloom-gfn1-header-") as directory:
            executable = Path(directory) / "header_test"
            subprocess.run(
                (
                    compiler,
                    "-std=c++17",
                    "-Wall",
                    "-Wextra",
                    "-Werror",
                    "-I",
                    str(REPOSITORY),
                    str(Path(__file__).with_name("gfn1_header_test.cpp")),
                    "-o",
                    str(executable),
                ),
                check=True,
            )
            subprocess.run((str(executable),), check=True)


if __name__ == "__main__":
    unittest.main()
