"""Offline validation for the canonical GFN1-xTB parameter bundle."""

from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

import tomllib

REPOSITORY = Path(__file__).resolve().parents[2]
DATA_DIR = REPOSITORY / "data" / "parameters"
GENERATOR_PATH = REPOSITORY / "tools" / "parameters" / "generate_gfn1.py"
SPEC = importlib.util.spec_from_file_location("xtbloom_generate_gfn1", GENERATOR_PATH)
assert SPEC is not None and SPEC.loader is not None
GENERATOR = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(GENERATOR)


class Gfn1ParameterTests(unittest.TestCase):
    """Verify GFN1-specific model tables, provenance, and generated bytes."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.raw_bytes = (DATA_DIR / GENERATOR.RAW_FILENAME).read_bytes()
        cls.raw = tomllib.loads(cls.raw_bytes.decode("utf-8"))
        cls.normalized = json.loads(
            (DATA_DIR / GENERATOR.JSON_FILENAME).read_text(encoding="utf-8")
        )
        cls.manifest = json.loads(
            (DATA_DIR / GENERATOR.MANIFEST_FILENAME).read_text(encoding="utf-8")
        )

    def test_complete_export_round_trips(self) -> None:
        mctc_parameters = self.manifest["mctc"]["parameters"]
        self.assertEqual(
            GENERATOR.normalize_export(self.raw, mctc_parameters), self.normalized
        )
        self.assertEqual(self.normalized["method"], "gfn1-xtb")
        self.assertEqual(len(self.normalized["elements"]), 86)
        self.assertEqual(
            sum(len(element["shells"]) for element in self.normalized["elements"]),
            237,
        )

    def test_gfn1_specific_global_models_are_explicit(self) -> None:
        self.assertEqual(self.normalized["dispersion"]["model"], "d3")
        self.assertFalse(self.normalized["dispersion"]["self_consistent"])
        self.assertEqual(self.normalized["hamiltonian"]["coordination_number"], "exp")
        self.assertEqual(self.normalized["charge"]["average"], "harmonic")
        self.assertEqual(self.normalized["thirdorder"]["mode"], "atom")
        self.assertFalse(self.normalized["thirdorder"]["shell_resolved"])

    def test_mctc_atomic_inputs_and_exponential_cn_are_complete(self) -> None:
        """Bind the non-TOML H0, halogen, and CN inputs used by GFN1."""
        coordination = self.normalized["coordination_number"]
        self.assertEqual(coordination["model"], "exp")
        self.assertEqual(coordination["steepness"], 16.0)
        self.assertEqual(coordination["cutoff_bohr"], 25.0)
        self.assertIsNone(coordination["maximum_cn_cutoff"])
        self.assertEqual(coordination["directed_factor"], 1.0)
        self.assertEqual(
            coordination["coincident_distance_squared_cutoff_bohr2"], 1.0e-12
        )
        self.assertTrue(coordination["cutoff_inclusive"])
        self.assertTrue(coordination["coincident_cutoff_inclusive"])
        self.assertEqual(
            coordination["pair_loop"],
            "lower triangle including diagonal over lattice translations",
        )
        self.assertIn("r_cov_i + r_cov_j", coordination["count_expression"])
        self.assertIn("expterm", coordination["derivative_expression"])

        hydrogen = self.normalized["elements"][0]
        radon = self.normalized["elements"][-1]
        self.assertEqual(hydrogen["en"], 2.2)
        self.assertEqual(hydrogen["atomic_radius_bohr"].hex(), "0x1.359cdbc254a45p-1")
        self.assertEqual(hydrogen["covalent_radius_bohr"].hex(), "0x1.9cd125031b85cp-1")
        self.assertEqual(radon["atomic_number"], 86)
        self.assertGreater(radon["atomic_radius_bohr"], 0.0)
        self.assertGreater(radon["covalent_radius_bohr"], 0.0)

    def test_mctc_provenance_binds_sources_conversion_and_license(self) -> None:
        """Require the reviewed v0.5.2 source and legal records."""
        mctc = self.manifest["mctc"]
        self.assertEqual(mctc["revision"], GENERATOR.MCTC_REVISION)
        self.assertEqual(mctc["tree"], GENERATOR.MCTC_TREE)
        self.assertEqual(mctc["license"], "Apache-2.0")
        self.assertEqual(
            mctc["parameters"]["angstrom_to_bohr"].hex(), "0x1.e3c5175fa440bp+0"
        )
        self.assertEqual(
            {record["path"] for record in mctc["sources"]},
            set(GENERATOR.MCTC_SOURCE_PATHS),
        )
        self.assertEqual(
            mctc["legal_files"],
            [
                {
                    "bytes": 11358,
                    "git_blob": "d645695673349e3947e8e5ae42332d0ac3164cd7",
                    "path": "LICENSE",
                    "sha256": (
                        "cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30"
                    ),
                }
            ],
        )
        self.assertEqual(
            self.normalized["halogen"], {"damping": 0.44, "radius_scale": 1.3}
        )

    def test_atomwise_third_order_and_halogen_strengths_survive(self) -> None:
        by_symbol = {
            element["symbol"]: element for element in self.normalized["elements"]
        }
        self.assertEqual(by_symbol["He"]["gam3"], 0.15)
        self.assertEqual(by_symbol["F"]["gam3"], 0.1615037)
        self.assertEqual(by_symbol["Cl"]["xbond"], 0.0)
        self.assertEqual(by_symbol["Br"]["xbond"], 0.0381742)
        self.assertEqual(by_symbol["I"]["xbond"], 0.0321944)
        self.assertEqual(by_symbol["At"]["xbond"], 0.022)

    def test_pair_override_table_is_complete_and_symmetric(self) -> None:
        overrides = self.normalized["hamiltonian"]["pair_scale_overrides"]
        self.assertEqual(len(overrides), 869)
        table = {tuple(entry["atomic_numbers"]): entry["value"] for entry in overrides}
        self.assertEqual(table[(1, 1)], 0.96)
        self.assertEqual(table[(1, 5)], 0.95)
        self.assertEqual(table[(1, 28)], 0.9)
        self.assertEqual(table[(1, 75)], 0.8)
        self.assertEqual(table[(21, 39)], 1.15)
        self.assertEqual(table[(39, 39)], 1.2)
        self.assertEqual(self.normalized["hamiltonian"]["pair_scale_default"], 1.0)

    def test_repeated_angular_momentum_shell_marks_only_first_valence(self) -> None:
        hydrogen = self.normalized["elements"][0]
        self.assertEqual(
            [shell["principal_quantum_number"] for shell in hydrogen["shells"]], [1, 2]
        )
        self.assertEqual(
            [shell["angular_momentum"] for shell in hydrogen["shells"]], [0, 0]
        )
        self.assertEqual(
            [shell["is_valence"] for shell in hydrogen["shells"]], [True, False]
        )
        self.assertEqual(
            [shell["reference_occupation"] for shell in hydrogen["shells"]], [1.0, 0.0]
        )

    def test_repeated_shell_with_nonzero_occupation_is_rejected(self) -> None:
        invalid = copy.deepcopy(self.raw)
        invalid["element"]["H"]["refocc"][1] = 1.0
        with self.assertRaisesRegex(GENERATOR.ParameterError, "must have zero refocc"):
            GENERATOR.normalize_export(invalid)

    def test_wrong_gfn1_algorithm_selectors_are_rejected(self) -> None:
        for path, value, message in (
            (("hamiltonian", "xtb", "cn"), "dexp", "coordination-number"),
            (("charge", "effective", "average"), "arithmetic", "charge average"),
            (("thirdorder", "shell"), True, "atomwise"),
        ):
            invalid = copy.deepcopy(self.raw)
            target = invalid
            for key in path[:-1]:
                target = target[key]
            target[path[-1]] = value
            with self.assertRaisesRegex(GENERATOR.ParameterError, message):
                GENERATOR.normalize_export(invalid)

    def test_manifest_pins_release_source_and_diagnostic_cross_check(self) -> None:
        self.assertEqual(
            self.manifest["source"]["revision"],
            "fa8a4416e8fe093d0075bc10ac875494c2a449a9",
        )
        self.assertEqual(
            self.manifest["source"]["tree"],
            "2cfe9e53c6413bd022e36346d62ba110c1c42f57",
        )
        source_records = self.manifest["source"]["parameter_sources"]
        self.assertEqual(len(source_records), 26)
        self.assertEqual(
            source_records[0],
            {
                "bytes": 3340,
                "git_blob": "e64bc8554699d29605ff96ffb81228fd1cb816d6",
                "path": "app/driver_param.f90",
                "sha256": (
                    "1eac18001d504affeb43e97f20b636f7d8b359a7e635dc455fa49a22f4be7c5d"
                ),
            },
        )
        self.assertEqual(
            self.manifest["inspection"]["revision"],
            "133f91efb94b47f05848e1f86832f40a1accc385",
        )
        classification = self.manifest["inspection"]["reviewed_classification"]
        self.assertIn("substantive later runtime-equation changes", classification)
        self.assertIn("non-authoritative", classification)
        self.assertIn(
            "not used to generate the canonical parameter bytes", classification
        )
        cross_check = self.manifest["cross_check"]
        self.assertEqual(cross_check["role"], "non-authoritative semantic cross-check")
        self.assertEqual(
            cross_check["tree"], "502d629acb0a9b1f93e829ec6f467f0beeb129eb"
        )
        self.assertEqual(
            cross_check["git_blob"], "917f562cba5bca5f02924d1d17d8946c7e64bc57"
        )
        self.assertEqual(cross_check["maximum_ulp_difference"], 2)
        self.assertEqual(cross_check["differing_binary64_values"], 157)
        for filename, metadata in self.manifest["outputs"].items():
            content = (DATA_DIR / filename).read_bytes()
            self.assertEqual(len(content), metadata["bytes"])
            self.assertEqual(hashlib.sha256(content).hexdigest(), metadata["sha256"])

    def test_offline_regeneration_is_byte_deterministic(self) -> None:
        provenance = {
            key: self.manifest[key]
            for key in ("source", "inspection", "exporter", "cross_check", "mctc")
        }
        generated = GENERATOR.build_artifacts(self.raw_bytes, provenance)
        for filename, content in generated.items():
            self.assertEqual(content, (DATA_DIR / filename).read_bytes(), filename)

    def test_stale_generated_file_is_rejected(self) -> None:
        provenance = {
            key: self.manifest[key]
            for key in ("source", "inspection", "exporter", "cross_check", "mctc")
        }
        generated = GENERATOR.build_artifacts(self.raw_bytes, provenance)
        with tempfile.TemporaryDirectory(prefix="xtbloom-gfn1-stale-") as directory:
            output = Path(directory)
            GENERATOR.write_or_check(output, generated, check=False)
            (output / GENERATOR.HEADER_FILENAME).write_bytes(b"stale\n")
            with self.assertRaisesRegex(GENERATOR.ParameterError, "gfn1.hpp"):
                GENERATOR.write_or_check(output, generated, check=True)

    def test_offline_regeneration_rejects_modified_nested_provenance(self) -> None:
        """Do not let retained source or cross-check hashes bless themselves."""
        for section, field in (
            ("source", "parameter_sources_sha256"),
            ("cross_check", "sha256"),
            ("mctc", "license_sha256"),
        ):
            with self.subTest(section=section, field=field):
                provenance = {
                    key: copy.deepcopy(self.manifest[key])
                    for key in (
                        "source",
                        "inspection",
                        "exporter",
                        "cross_check",
                        "mctc",
                    )
                }
                provenance[section][field] = "0" * 64
                with self.assertRaisesRegex(
                    GENERATOR.ParameterError, "retained provenance differs"
                ):
                    GENERATOR.build_artifacts(self.raw_bytes, provenance)

    def test_generated_header_compiles(self) -> None:
        compiler = shutil.which("c++")
        if compiler is None:
            self.skipTest("C++ compiler is unavailable")
        with tempfile.TemporaryDirectory(prefix="xtbloom-gfn1-header-") as directory:
            executable = Path(directory) / "header_test"
            subprocess.run(
                (
                    compiler,
                    "-std=c++17",
                    "-Wall",
                    "-Wextra",
                    "-Werror",
                    "-I",
                    str(REPOSITORY),
                    str(Path(__file__).with_name("gfn1_header_test.cpp")),
                    "-o",
                    str(executable),
                ),
                check=True,
            )
            subprocess.run((str(executable),), check=True)


if __name__ == "__main__":
    unittest.main()
