"""Offline validation for the complete GFN1 simple-dftd3 table bundle."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[2]
DATA_DIR = REPOSITORY / "data" / "parameters"
GENERATOR_PATH = REPOSITORY / "tools" / "parameters" / "generate_gfn1_d3.py"
SPEC = importlib.util.spec_from_file_location(
    "xtbloom_generate_gfn1_d3", GENERATOR_PATH
)
assert SPEC is not None and SPEC.loader is not None
GENERATOR = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(GENERATOR)


class Gfn1D3ParameterTests(unittest.TestCase):
    """Verify table completeness, indexing, provenance, and generated bytes."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.tables = GENERATOR.validate_tables(
            json.loads((DATA_DIR / GENERATOR.JSON_FILENAME).read_text(encoding="utf-8"))
        )
        cls.manifest = json.loads(
            (DATA_DIR / GENERATOR.MANIFEST_FILENAME).read_text(encoding="utf-8")
        )

    def test_complete_element_reference_and_pair_counts(self) -> None:
        self.assertEqual(len(self.tables["elements"]), 86)
        self.assertEqual(len(self.tables["coordination_numbers"]), 237)
        self.assertEqual(len(self.tables["pair_records"]), 86 * 87 // 2)
        self.assertEqual(len(self.tables["vdw_radii"]), 86 * 87 // 2)
        self.assertEqual(len(self.tables["c6"]), 28455)
        self.assertTrue(all(value > 0.0 for value in self.tables["c6"]))

    def test_reference_offsets_and_element_boundaries(self) -> None:
        first = self.tables["elements"][0]
        cerium = self.tables["elements"][57]
        last = self.tables["elements"][-1]
        self.assertEqual(first, {"reference_offset": 0, "reference_count": 2})
        self.assertEqual(cerium, {"reference_offset": 166, "reference_count": 1})
        self.assertEqual(last, {"reference_offset": 236, "reference_count": 1})
        self.assertEqual(self.tables["coordination_numbers"][:2], [0.9118, 0.0])
        self.assertEqual(self.tables["coordination_numbers"][166], 2.7991)
        self.assertEqual(self.tables["coordination_numbers"][-1], 0.0)

    def test_packed_c6_layout_matches_fortran_get_c6_contract(self) -> None:
        def block(first: int, second: int) -> list[float]:
            pair_index = (first - 1) + second * (second - 1) // 2
            record = self.tables["pair_records"][pair_index]
            size = record["first_reference_count"] * record["second_reference_count"]
            offset = record["c6_offset"]
            return self.tables["c6"][offset : offset + size]

        self.assertEqual(block(1, 1), [3.0267, 4.7379, 4.7379, 7.5916])
        self.assertEqual(block(1, 2), [2.0835, 3.1287])
        self.assertEqual(block(1, 6)[:4], [12.1402, 19.2653, 11.3932, 18.0575])
        self.assertEqual(block(1, 86), [35.275, 55.4345])
        self.assertEqual(block(86, 86), [412.8275])

    def test_r4r2_and_vdw_units_cover_representative_boundaries(self) -> None:
        self.assertEqual(self.tables["angstrom_to_bohr"], 1.8897261246204404)
        self.assertAlmostEqual(self.tables["r4r2"][0], 2.00734899805689)
        self.assertAlmostEqual(self.tables["r4r2"][5], 3.104928220612981)
        self.assertAlmostEqual(self.tables["r4r2"][-1], 6.095279657044429)
        self.assertAlmostEqual(self.tables["vdw_radii"][0], 4.123949321759188)
        self.assertAlmostEqual(self.tables["vdw_radii"][-1], 7.032804745387431)

    def test_manifest_pins_every_source_and_legal_blob(self) -> None:
        self.assertEqual(
            self.manifest["source"]["revision"], GENERATOR.UPSTREAM_REVISION
        )
        self.assertEqual(self.manifest["source"]["tree"], GENERATOR.UPSTREAM_TREE)
        self.assertEqual(
            self.manifest["unit_conversion"]["revision"], GENERATOR.MCTC_REVISION
        )
        self.assertEqual(self.manifest["unit_conversion"]["tree"], GENERATOR.MCTC_TREE)
        legal = {
            record["path"]: record["sha256"]
            for record in self.manifest["source"]["legal_files"]
        }
        self.assertEqual(
            legal,
            {
                "COPYING": "".join(
                    (
                        "3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66",
                        "d6af86c9dfb36986",
                    )
                ),
                "COPYING.LESSER": "".join(
                    (
                        "e3a994d82e644b03a792a930f574002658412f62407f5fee",
                        "083f2555c5f23118",
                    )
                ),
            },
        )
        output = (DATA_DIR / GENERATOR.HEADER_FILENAME).read_bytes()
        self.assertEqual(
            hashlib.sha256(output).hexdigest(),
            self.manifest["outputs"][GENERATOR.HEADER_FILENAME]["sha256"],
        )

    def test_regeneration_is_deterministic_and_stale_files_are_rejected(self) -> None:
        artifacts = GENERATOR.build_offline_artifacts(DATA_DIR)
        for filename, content in artifacts.items():
            self.assertEqual(content, (DATA_DIR / filename).read_bytes(), filename)
        with tempfile.TemporaryDirectory(prefix="xtbloom-gfn1-d3-stale-") as directory:
            output = Path(directory)
            GENERATOR.write_or_check(output, artifacts, check=False)
            (output / GENERATOR.HEADER_FILENAME).write_bytes(b"stale\n")
            with self.assertRaisesRegex(GENERATOR.D3DataError, "gfn1_d3.hpp"):
                GENERATOR.write_or_check(output, artifacts, check=True)

    def test_optional_upstream_refresh_matches_retained_bundle(self) -> None:
        """Recheck the pinned Git blobs when explicit local sources are supplied."""
        d3_source = os.environ.get("XTBLOOM_SIMPLE_DFTD3_SOURCE")
        mctc_source = os.environ.get("XTBLOOM_MCTC_SOURCE")
        if not d3_source or not mctc_source:
            self.skipTest(
                "set XTBLOOM_SIMPLE_DFTD3_SOURCE and XTBLOOM_MCTC_SOURCE "
                "to audit upstream Git blobs"
            )
        refreshed = GENERATOR.build_artifacts(
            Path(d3_source),
            GENERATOR.UPSTREAM_REVISION,
            Path(mctc_source),
            GENERATOR.MCTC_REVISION,
        )
        for filename, content in refreshed.items():
            self.assertEqual(content, (DATA_DIR / filename).read_bytes(), filename)

    def test_normalized_schema_rejects_corrupt_pair_offsets(self) -> None:
        normalized = json.loads(
            (DATA_DIR / GENERATOR.JSON_FILENAME).read_text(encoding="utf-8")
        )
        normalized["pair_records"][1]["c6_offset"] += 1
        with self.assertRaisesRegex(GENERATOR.D3DataError, "invalid C6 packing"):
            GENERATOR.validate_tables(normalized)

    def test_generated_header_compiles(self) -> None:
        compiler = shutil.which("c++")
        if compiler is None:
            self.skipTest("C++ compiler is unavailable")
        with tempfile.TemporaryDirectory(prefix="xtbloom-gfn1-d3-header-") as directory:
            executable = Path(directory) / "header_test"
            subprocess.run(
                (
                    compiler,
                    "-std=c++17",
                    "-Wall",
                    "-Wextra",
                    "-Werror",
                    "-I",
                    str(REPOSITORY),
                    str(Path(__file__).with_name("gfn1_d3_header_test.cpp")),
                    "-o",
                    str(executable),
                ),
                check=True,
            )
            subprocess.run((str(executable),), check=True)


if __name__ == "__main__":
    unittest.main()
