"""Offline validation for the complete GFN1 simple-dftd3 table bundle."""

from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import os
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[2]
DATA_DIR = REPOSITORY / "data" / "parameters"
GENERATOR_PATH = REPOSITORY / "tools" / "parameters" / "generate_gfn1_d3.py"
SPEC = importlib.util.spec_from_file_location(
    "xtbloom_generate_gfn1_d3", GENERATOR_PATH
)
assert SPEC is not None and SPEC.loader is not None
GENERATOR = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(GENERATOR)


class Gfn1D3ParameterTests(unittest.TestCase):
    """Verify table completeness, indexing, provenance, and generated bytes."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.tables = GENERATOR.validate_tables(
            json.loads((DATA_DIR / GENERATOR.JSON_FILENAME).read_text(encoding="utf-8"))
        )
        cls.manifest = json.loads(
            (DATA_DIR / GENERATOR.MANIFEST_FILENAME).read_text(encoding="utf-8")
        )

    def test_complete_element_reference_and_pair_counts(self) -> None:
        self.assertEqual(len(self.tables["elements"]), 86)
        self.assertEqual(len(self.tables["coordination_numbers"]), 237)
        self.assertEqual(len(self.tables["pair_records"]), 86 * 87 // 2)
        self.assertEqual(len(self.tables["vdw_radii"]), 86 * 87 // 2)
        self.assertEqual(len(self.tables["c6"]), 28455)
        self.assertTrue(all(value > 0.0 for value in self.tables["c6"]))

    def test_reference_offsets_and_element_boundaries(self) -> None:
        first = self.tables["elements"][0]
        cerium = self.tables["elements"][57]
        last = self.tables["elements"][-1]
        self.assertEqual(first, {"reference_offset": 0, "reference_count": 2})
        self.assertEqual(cerium, {"reference_offset": 166, "reference_count": 1})
        self.assertEqual(last, {"reference_offset": 236, "reference_count": 1})
        self.assertEqual(self.tables["coordination_numbers"][:2], [0.9118, 0.0])
        self.assertEqual(self.tables["coordination_numbers"][166], 2.7991)
        self.assertEqual(self.tables["coordination_numbers"][-1], 0.0)

    def test_packed_c6_layout_matches_fortran_get_c6_contract(self) -> None:
        def block(first: int, second: int) -> list[float]:
            pair_index = (first - 1) + second * (second - 1) // 2
            record = self.tables["pair_records"][pair_index]
            size = record["first_reference_count"] * record["second_reference_count"]
            offset = record["c6_offset"]
            return self.tables["c6"][offset : offset + size]

        self.assertEqual(block(1, 1), [3.0267, 4.7379, 4.7379, 7.5916])
        self.assertEqual(block(1, 2), [2.0835, 3.1287])
        self.assertEqual(block(1, 6)[:4], [12.1402, 19.2653, 11.3932, 18.0575])
        self.assertEqual(block(1, 86), [35.275, 55.4345])
        self.assertEqual(block(86, 86), [412.8275])

    def test_r4r2_and_vdw_units_cover_representative_boundaries(self) -> None:
        self.assertEqual(self.tables["angstrom_to_bohr"], 1.8897261246204404)
        self.assertAlmostEqual(self.tables["r4r2"][0], 2.00734899805689)
        self.assertAlmostEqual(self.tables["r4r2"][5], 3.104928220612981)
        self.assertAlmostEqual(self.tables["r4r2"][-1], 6.095279657044429)
        self.assertAlmostEqual(self.tables["vdw_radii"][0], 4.123949321759188)
        self.assertAlmostEqual(self.tables["vdw_radii"][-1], 7.032804745387431)

    def test_manifest_pins_every_source_and_legal_blob(self) -> None:
        self.assertEqual(
            self.manifest["source"]["revision"], GENERATOR.UPSTREAM_REVISION
        )
        self.assertEqual(self.manifest["source"]["tree"], GENERATOR.UPSTREAM_TREE)
        self.assertEqual(
            self.manifest["unit_conversion"]["revision"], GENERATOR.MCTC_REVISION
        )
        self.assertEqual(self.manifest["unit_conversion"]["tree"], GENERATOR.MCTC_TREE)
        legal = {
            record["path"]: record["sha256"]
            for record in self.manifest["source"]["legal_files"]
        }
        self.assertEqual(
            legal,
            {
                "COPYING": "".join(
                    (
                        "3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66",
                        "d6af86c9dfb36986",
                    )
                ),
                "COPYING.LESSER": "".join(
                    (
                        "e3a994d82e644b03a792a930f574002658412f62407f5fee",
                        "083f2555c5f23118",
                    )
                ),
            },
        )
        self.assertEqual(
            self.manifest["unit_conversion"]["legal_files"],
            [
                {
                    "bytes": 11358,
                    "git_blob": "d645695673349e3947e8e5ae42332d0ac3164cd7",
                    "path": "LICENSE",
                    "sha256": (
                        "cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30"
                    ),
                }
            ],
        )
        equations = {
            record["path"]: (record["git_blob"], record["sha256"])
            for record in self.manifest["source"]["equation_sources"]
        }
        self.assertEqual(
            equations,
            {
                "src/dftd3/model.f90": (
                    "41d3eb76915c05c515ce1802efc8ba8213c0cd42",
                    "b4b2cad1f772263c979ea2674b6d5d78f4eec19fa91a13afd3a789d0a7e866df",
                ),
                "src/dftd3/damping/rational.f90": (
                    "a8edb7c50b08fde56f234750a2155053a0102bfa",
                    "d3a9fca2c45ebc4c3b88a49d7688774904f78b7fbacd2716f3756dc5f55521e8",
                ),
                "src/dftd3/disp.f90": (
                    "413683f9a16b8621875bf1880af764f63e2ac02d",
                    "cf2e68d8afb1c33b1f458dd09360e512c7171686d8e371a29d02501e0458edde",
                ),
                "src/dftd3/cutoff.f90": (
                    "743774e355c6e99aac49c0288be8593b08237c9c",
                    "c98c15fa8f38e961bf920cff176daa649b48f685b28a4b5dd04860ca0c19fd29",
                ),
            },
        )
        execution = self.manifest["execution_contract"]
        self.assertEqual(execution["two_body_cutoff_bohr"], 50.0)
        self.assertEqual(execution["smooth_cutoff_width_bohr"], 0.05)
        self.assertEqual(
            {
                record["path"]: (record["git_blob"], record["sha256"])
                for record in execution["sources"]
            },
            {
                "src/tblite/disp/d3.f90": (
                    "df1b9cfe8e45078c021c55359c758506efae7210",
                    "b4a8d386fd30723cc7bebf7ced4f5a08c1ed4bae58ca753e4e2dcdaf92a4029c",
                ),
                "src/tblite/xtb/calculator.f90": (
                    "31e1394455e0f1fc77f3dfc0dfd7cc14abd36e38",
                    "40a44bfe99b0d6aa11d6d9de18ae1f12cfbd32e73eaf344c88492de46927818d",
                ),
                "src/tblite/xtb/gfn1.f90": (
                    "dc96235fa5bd0ece28f9a7e3672716cfea3633b6",
                    "0df0d3eca4b69efa445733a2fda269220cb203fb325acf0f6f06c21c55feb630",
                ),
            },
        )
        output = (DATA_DIR / GENERATOR.HEADER_FILENAME).read_bytes()
        self.assertEqual(
            hashlib.sha256(output).hexdigest(),
            self.manifest["outputs"][GENERATOR.HEADER_FILENAME]["sha256"],
        )

    def test_regeneration_is_deterministic_and_stale_files_are_rejected(self) -> None:
        artifacts = GENERATOR.build_offline_artifacts(DATA_DIR)
        for filename, content in artifacts.items():
            self.assertEqual(content, (DATA_DIR / filename).read_bytes(), filename)
        with tempfile.TemporaryDirectory(prefix="xtbloom-gfn1-d3-stale-") as directory:
            output = Path(directory)
            GENERATOR.write_or_check(output, artifacts, check=False)
            (output / GENERATOR.HEADER_FILENAME).write_bytes(b"stale\n")
            with self.assertRaisesRegex(GENERATOR.D3DataError, "gfn1_d3.hpp"):
                GENERATOR.write_or_check(output, artifacts, check=True)

    def test_offline_regeneration_rejects_modified_nested_provenance(self) -> None:
        """Reject a retained mctc source digest before regenerating outputs."""
        manifest = copy.deepcopy(self.manifest)
        manifest["unit_conversion"]["sources"][0]["sha256"] = "0" * 64
        with tempfile.TemporaryDirectory(
            prefix="xtbloom-gfn1-d3-provenance-"
        ) as directory:
            output = Path(directory)
            shutil.copy2(DATA_DIR / GENERATOR.JSON_FILENAME, output)
            (output / GENERATOR.MANIFEST_FILENAME).write_text(
                json.dumps(manifest, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(
                GENERATOR.D3DataError, "retained provenance differs"
            ):
                GENERATOR.build_offline_artifacts(output)

    def test_optional_upstream_refresh_matches_retained_bundle(self) -> None:
        """Recheck the pinned Git blobs when explicit local sources are supplied."""
        d3_source = os.environ.get("XTBLOOM_SIMPLE_DFTD3_SOURCE")
        mctc_source = os.environ.get("XTBLOOM_MCTC_SOURCE")
        tblite_source = os.environ.get("XTBLOOM_TBLITE_SOURCE")
        if not d3_source or not mctc_source or not tblite_source:
            self.skipTest(
                "set XTBLOOM_SIMPLE_DFTD3_SOURCE, XTBLOOM_MCTC_SOURCE, and "
                "XTBLOOM_TBLITE_SOURCE to audit upstream Git blobs"
            )
        refreshed = GENERATOR.build_artifacts(
            Path(d3_source),
            GENERATOR.UPSTREAM_REVISION,
            Path(mctc_source),
            GENERATOR.MCTC_REVISION,
            Path(tblite_source),
            GENERATOR.TBLITE_REVISION,
        )
        for filename, content in refreshed.items():
            self.assertEqual(content, (DATA_DIR / filename).read_bytes(), filename)

    def test_normalized_schema_rejects_corrupt_pair_offsets(self) -> None:
        normalized = json.loads(
            (DATA_DIR / GENERATOR.JSON_FILENAME).read_text(encoding="utf-8")
        )
        normalized["pair_records"][1]["c6_offset"] += 1
        with self.assertRaisesRegex(GENERATOR.D3DataError, "invalid C6 packing"):
            GENERATOR.validate_tables(normalized)

    def test_upstream_array_unit_prefixes_are_exact(self) -> None:
        """Reject an upstream unit-expression change before applying conversion."""
        raw = "real(wp), parameter :: sample(2) = [1.0_wp, 2.0_wp]"
        self.assertEqual(
            GENERATOR._parameter_array(raw, "sample", 2, prefix=""), [1.0, 2.0]
        )
        with self.assertRaisesRegex(GENERATOR.D3DataError, "expected upstream"):
            GENERATOR._parameter_array(raw, "sample", 2, prefix=r"aatoau\s*\*\s*")
        scaled = "real(wp), parameter :: sample(2) = aatoau * [1.0_wp, 2.0_wp]"
        self.assertEqual(
            GENERATOR._parameter_array(scaled, "sample", 2, prefix=r"aatoau\s*\*\s*"),
            [1.0, 2.0],
        )
        with self.assertRaisesRegex(GENERATOR.D3DataError, "expected upstream"):
            GENERATOR._parameter_array(scaled, "sample", 2, prefix="")

    def test_generated_header_compiles(self) -> None:
        compiler = shutil.which("c++")
        if compiler is None:
            self.skipTest("C++ compiler is unavailable")
        with tempfile.TemporaryDirectory(prefix="xtbloom-gfn1-d3-header-") as directory:
            executable = Path(directory) / "header_test"
            subprocess.run(
                (
                    compiler,
                    "-std=c++17",
                    "-Wall",
                    "-Wextra",
                    "-Werror",
                    "-I",
                    str(REPOSITORY),
                    str(Path(__file__).with_name("gfn1_d3_header_test.cpp")),
                    "-o",
                    str(executable),
                ),
                check=True,
            )
            subprocess.run((str(executable),), check=True)


if __name__ == "__main__":
    unittest.main()
