// gpuxtb CPU SCC trace harness shared by the single-case capture, the ragged
// batch capture, and the golden mixed-state replay executables (issues
// #42/#49/#50).
//
// Reads corpus case.spec files (the same fixed layout emitted by
// generate_scc_corpus.py), drives the production CPU GFN2 SCC driver for one
// or more systems in one ragged batch, and streams captured per-iteration
// state in exactly the same raw layout as the Fortran tblite recorder so that
// generate_scc_corpus.canonicalize() can assemble gpuxtb-scc-trace-v1
// documents and the comparator can compare them against pinned goldens.
//
// The harness seeds the SCC perturbative q/d/Q state at exactly zero (matching
// tblite's new_wavefunction) and enables the self-consistent D4 two-body
// potential, because the pinned goldens were generated by a GFN2 single point
// that includes D4 and starts from that zero-charge state.  A production SAD
// seed or a D4-less driver would move the first mixed state and every
// following Hamiltonian away from the golden trajectory.
//
// This header is test-only tooling against internal GFN2 headers; it is not
// part of the public C ABI.
#ifndef GPUXTB_TESTS_SUPPORT_SCC_TRACE_HARNESS_HPP
#define GPUXTB_TESTS_SUPPORT_SCC_TRACE_HARNESS_HPP

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iosfwd>
#include <iostream>
#include <limits>
#include <memory>
#include <new>
#include <string>
#include <utility>
#include <vector>

#include "gpuxtb/gpuxtb.h"
#include "model/gfn2/aes2.hpp"
#include "model/gfn2/basis.hpp"
#include "model/gfn2/coordination.hpp"
#include "model/gfn2/d4.hpp"
#include "model/gfn2/eigensolver.hpp"
#include "model/gfn2/es2.hpp"
#include "model/gfn2/es3.hpp"
#include "model/gfn2/external_point_charges.hpp"
#include "model/gfn2/h0.hpp"
#include "model/gfn2/integrals.hpp"
#include "model/gfn2/mulliken.hpp"
#include "model/gfn2/scc_driver.hpp"
#include "model/gfn2/scc_mixer.hpp"
#include "model/gfn2/wavefunction.hpp"

namespace gpuxtb_trace_harness {

using namespace gpuxtb::detail::gfn2;

inline constexpr double kKelvinToHartree = 3.166808578545117e-6;
// Match tblite's singlepoint convergence policy exactly: with accuracy=1.0
// the electronic energy gate is econv = 1.0e-6*accuracy and the population
// gate is pconv = 2.0e-5*accuracy.  The goldens were generated by that pinned
// policy, so closed-loop and replay comparisons are only meaningful when the
// CPU driver uses the same thresholds.
inline constexpr double kTbliteEnergyTolerance = 1.0e-6;
inline constexpr double kTbliteRmsTolerance = 2.0e-5;
// Iterations never legitimately reach this many for the pinned corpus.
inline constexpr std::uint64_t kMaximumHarnessIterations = 256u;

struct AlignedBuffer {
  void* data = nullptr;
  std::size_t size = 0u;
  explicit AlignedBuffer(std::size_t requested) {
    size = (std::max<std::size_t>(requested, 1u) + 63u) & ~std::size_t{63u};
    data = std::aligned_alloc(64u, size);
    if (data != nullptr) {
      std::memset(data, 0, size);
    }
  }
  ~AlignedBuffer() { std::free(data); }
  AlignedBuffer(const AlignedBuffer&) = delete;
  AlignedBuffer& operator=(const AlignedBuffer&) = delete;
};

struct CaseSpec {
  std::int64_t nat = 0;
  std::vector<std::int32_t> atomic_numbers;
  std::vector<double> positions;
  double molecular_charge = 0.0;
  std::int32_t unpaired_electrons = 0;
  double temperature_kelvin = 300.0;
  std::int64_t mixer_memory = 2;
  double mixer_damping = 0.4;
  std::int64_t maximum_iterations = 100;
  std::vector<double> pc_rows;  // x y z q gamma per point charge
};

inline bool load_spec(const std::string& path, CaseSpec& spec, std::string& err) {
  std::ifstream file(path);
  if (!file) {
    err = "cannot open spec " + path;
    return false;
  }
  if (!(file >> spec.nat)) {
    err = "missing atom count";
    return false;
  }
  spec.atomic_numbers.resize(static_cast<std::size_t>(spec.nat));
  for (auto& number : spec.atomic_numbers) {
    if (!(file >> number)) {
      err = "missing atomic number";
      return false;
    }
  }
  spec.positions.resize(static_cast<std::size_t>(spec.nat * 3));
  for (auto& value : spec.positions) {
    if (!(file >> value)) {
      err = "missing position";
      return false;
    }
  }
  if (!(file >> spec.molecular_charge)) {
    err = "missing charge";
    return false;
  }
  if (!(file >> spec.unpaired_electrons)) {
    err = "missing unpaired electrons";
    return false;
  }
  if (!(file >> spec.temperature_kelvin)) {
    err = "missing temperature";
    return false;
  }
  if (!(file >> spec.mixer_memory)) {
    err = "missing mixer memory";
    return false;
  }
  if (!(file >> spec.mixer_damping)) {
    err = "missing mixer damping";
    return false;
  }
  if (!(file >> spec.maximum_iterations)) {
    err = "missing max iterations";
    return false;
  }
  std::int64_t npc = 0;
  if (!(file >> npc)) {
    err = "missing point-charge count";
    return false;
  }
  spec.pc_rows.resize(static_cast<std::size_t>(npc * 5));
  for (auto& value : spec.pc_rows) {
    if (!(file >> value)) {
      err = "missing point-charge value";
      return false;
    }
  }
  return true;
}

// One captured iteration in the raw stream section order.  The logical index
// matches the golden's iterations[i].index.
struct CapturedIteration {
  std::vector<double> hamiltonian, eigenvalues, occupations_alpha, occupations_beta, density;
  std::vector<double> mixed_qsh, mixed_qat, mixed_dipoles, mixed_quadrupoles;
  std::vector<double> raw_qsh, raw_qat, raw_dipoles, raw_quadrupoles;
  std::vector<double> point_charge_shell_potential, point_charge_energy;
  double energy = 0.0;
  double energy_delta = 0.0;
  double residual_rms = 0.0;
  int econv = 0;
  int pconv = 0;
  int tconv = 1;
  int conv = 0;
};

/*
 * One ragged batch of corpus cases driven as a single GFN2 SCC driver plan.
 *
 * add_case() fills the batch, build() creates every plan/cache and seeds the
 * zero-charge state, then step()/run() advance the systems and emit() writes
 * each lane's raw recorder stream.  poison_h0() marks one lane as a controlled
 * per-system preparation failure, and inject_mixed_state() +
 * set_replay_context() seed one lane from a golden mixed state for the
 * single-iteration replay (issue #49).
 */
class TraceBatch {
 public:
  TraceBatch() = default;
  TraceBatch(const TraceBatch&) = delete;
  TraceBatch& operator=(const TraceBatch&) = delete;

  std::int64_t system_count() const noexcept { return static_cast<std::int64_t>(specs_.size()); }
  const CaseSpec& spec(std::int64_t index) const {
    return specs_[static_cast<std::size_t>(index)];
  }

  gpuxtb_status_t system_status(std::int64_t index) const;
  std::uint64_t system_iterations(std::int64_t index) const;
  bool system_converged(std::int64_t index) const;
  // Live per-system multipole slice {qsh, qat, dipoles, quadrupoles}, for
  // native tests that verify output placement and early-convergence freezing.
  std::vector<std::vector<double>> live_state(std::int64_t system) const;
  const std::vector<CapturedIteration>& iterations(std::int64_t index) const {
    return iterations_[static_cast<std::size_t>(index)];
  }

  void add_case(const CaseSpec& spec) { specs_.push_back(spec); }

  gpuxtb_status_t build(std::string& err);
  // Write NaN into the H0 slice of one system so its next preparation phase
  // fails per-system without touching peers (controlled failure-isolation
  // member for issue #50).  Must be called after build() and before run().
  void poison_h0(std::int64_t system);
  // Inject the golden mixed q/d/Q state into one system before the first
  // step() (single-iteration replay for issue #49).  The state file layout is
  // line-oriented: "qsh <n>" then n values, "qat <n>" then n values,
  // "dipoles <n>" then n values, "quadrupoles <n>" then n values.
  gpuxtb_status_t inject_mixed_state(std::int64_t system, const std::string& state_path,
                                     std::string& err);
  // Choose the injected state's logical iteration number and previous internal
  // energy so a replay of golden iteration k computes the same energy_delta
  // and convergence flags as tblite.
  void set_replay_context(std::int64_t system, std::uint64_t logical_index,
                          double previous_energy);
  // Re-capture one system's mixer current input from the injected wavefunction
  // state and clear its history, so a single-iteration replay's residual is
  // raw minus the injected golden mixed state (not the zero init).
  gpuxtb_status_t restart_mixer_system(std::int64_t system, std::string& err);
  // Advance every active system by exactly one driver iteration.  Successful
  // peers are committed even when another lane failed.
  gpuxtb_status_t step(std::string& err);
  // One full harness iteration: capture pre-solve mixed state, advance every
  // active system by one driver iteration, and record the per-lane snapshots.
  gpuxtb_status_t step_once(std::string& err);
  // Loop step() until every system is terminal or kMaximumHarnessIterations
  // passes.  A per-lane failure (for example the poisoned lane) does not
  // suppress the successful lanes.
  gpuxtb_status_t run(std::string& err);
  // Append the complete raw stream of one system in the recorder layout.
  void emit(std::ostream& output, std::int64_t system) const;

 private:
  struct Geometry;
  struct Stage;

  gpuxtb_status_t build_geometry(std::string& err);
  gpuxtb_status_t build_stage(const CaseSpec& reference, std::string& err);
  // Capture the pre-solve mixed q/d/Q of every active lane before a step.
  void capture_mixed_pre_step();
  // Append one CapturedIteration for every lane that advanced this call,
  // pairing each raw/energy/convergence payload with the pre-solve mixed
  // state captured by capture_mixed_pre_step().
  void record_iteration_snapshots();

  std::vector<CaseSpec> specs_;
  std::shared_ptr<Geometry> geometry_;
  std::shared_ptr<Stage> stage_;
  std::vector<std::vector<CapturedIteration>> iterations_;
  // Pre-solve mixed state per lane: {qsh, qat, dipoles, quadrupoles}.
  std::vector<std::vector<std::vector<double>>> pending_mixed_;
};

struct TraceBatch::Geometry {
  std::int64_t batch_size = 1;
  std::vector<std::int64_t> atom_offsets;
  std::vector<std::int64_t> pc_offsets;
  std::vector<double> positions, pc_positions, pc_charges, pc_hardnesses;
  std::vector<double> molecular_charges;
  std::vector<std::int32_t> unpaired, spins;

  BasisPlan basis;
  IntegralPlan integrals;
  H0Plan h0_plan;
  WavefunctionLayout layout;
  ES2Plan es2_plan;
  ES3Plan es3_plan;
  AES2Plan aes2_plan;
  MullikenPlan mulliken_plan;
  EigensolverPlan eig_plan;
  CoordinationPlan coordination_plan;
  ExternalPointChargePlan pc_plan;
  D4Plan d4_plan;

  std::vector<double> overlap, dint, qint, h0, cn, pc_shell_potential;
  AlignedBuffer iscratch{1u << 20}, e2s{1u << 22}, e2scratch{1u << 22}, a2s{1u << 22},
      a2scratch{1u << 22}, d4_buffer{1u << 21};
  ES2GeometryCache es2_cache;
  AES2GeometryCache aes2_cache;
  ES2Workspace es2_ws;
  AES2Workspace aes2_ws;
  D4Workspace d4_ws;
  D4GeometryCache d4_cache;
  std::vector<double> d4_pairs, d4_coordination;

  AlignedBuffer wfn_s{1u << 22};
  WavefunctionView wfn;
  AlignedBuffer oc_s{1u << 22};
  EigensolverOverlapCache ocache;
  AlignedBuffer eig_s{1u << 22};
  EigensolverWorkspace eig_ws;
  CpuLinearAlgebraBackend backend;

  SccDriverGeometryView geom;
};

struct TraceBatch::Stage {
  SccMixerPlan mixer_plan;
  SccDriverPlan driver_plan;
  AlignedBuffer mixer_s{1u << 22};
  SccMixerState mixer_state;
  AlignedBuffer drv_s{1u << 22};
  SccDriverState driver_state;
  AlignedBuffer drvws_s{1u << 22};
  SccDriverWorkspace drv_ws;
};

gpuxtb_status_t TraceBatch::system_status(std::int64_t index) const {
  return stage_->driver_state.system_statuses[index];
}
std::uint64_t TraceBatch::system_iterations(std::int64_t index) const {
  return stage_->driver_state.iterations[index];
}
bool TraceBatch::system_converged(std::int64_t index) const {
  return stage_->driver_state.converged[index] != 0u;
}
std::vector<std::vector<double>> TraceBatch::live_state(std::int64_t system) const {
  const Geometry& g = *geometry_;
  const std::int64_t shell_begin = g.basis.batch_shell_offsets[system];
  const std::int64_t shell_end = g.basis.batch_shell_offsets[system + 1u];
  const std::int64_t qat_begin = g.layout.qat.system_offsets[system];
  const std::int64_t qat_end = g.layout.qat.system_offsets[system + 1u];
  const std::int64_t dip_begin = g.layout.dipole.system_offsets[system];
  const std::int64_t dip_end = g.layout.dipole.system_offsets[system + 1u];
  const std::int64_t quad_begin = g.layout.quadrupole.system_offsets[system];
  const std::int64_t quad_end = g.layout.quadrupole.system_offsets[system + 1u];
  return {
      std::vector<double>(g.wfn.qsh + shell_begin, g.wfn.qsh + shell_end),
      std::vector<double>(g.wfn.qat + qat_begin, g.wfn.qat + qat_end),
      std::vector<double>(g.wfn.dipole + dip_begin, g.wfn.dipole + dip_end),
      std::vector<double>(g.wfn.quadrupole + quad_begin, g.wfn.quadrupole + quad_end),
  };
}

gpuxtb_status_t TraceBatch::build_geometry(std::string& err) {
  auto geometry = std::make_shared<Geometry>();
  Geometry& g = *geometry;
  g.batch_size = static_cast<std::int64_t>(specs_.size());
  if (g.batch_size <= 0) {
    err = "trace harness needs at least one case";
    return GPUXTB_STATUS_INVALID_ARGUMENT;
  }

  std::int64_t total_atoms = 0;
  std::int64_t total_point_charges = 0;
  g.atom_offsets.assign(static_cast<std::size_t>(g.batch_size) + 1u, 0);
  g.pc_offsets.assign(static_cast<std::size_t>(g.batch_size) + 1u, 0);
  g.molecular_charges.resize(static_cast<std::size_t>(g.batch_size));
  g.unpaired.resize(static_cast<std::size_t>(g.batch_size));
  g.spins.assign(static_cast<std::size_t>(g.batch_size), 1);
  for (std::int64_t system = 0; system < g.batch_size; ++system) {
    const CaseSpec& spec = specs_[static_cast<std::size_t>(system)];
    g.atom_offsets[static_cast<std::size_t>(system + 1)] =
        g.atom_offsets[static_cast<std::size_t>(system)] + spec.nat;
    g.pc_offsets[static_cast<std::size_t>(system + 1)] =
        g.pc_offsets[static_cast<std::size_t>(system)] +
        static_cast<std::int64_t>(spec.pc_rows.size() / 5u);
    g.molecular_charges[static_cast<std::size_t>(system)] = spec.molecular_charge;
    g.unpaired[static_cast<std::size_t>(system)] = spec.unpaired_electrons;
  }
  total_atoms = g.atom_offsets[static_cast<std::size_t>(g.batch_size)];
  total_point_charges = g.pc_offsets[static_cast<std::size_t>(g.batch_size)];

  g.positions.reserve(static_cast<std::size_t>(3 * total_atoms));
  for (const CaseSpec& spec : specs_) {
    g.positions.insert(g.positions.end(), spec.positions.begin(), spec.positions.end());
  }
  for (const CaseSpec& spec : specs_) {
    const std::int64_t npc = static_cast<std::int64_t>(spec.pc_rows.size() / 5u);
    for (std::int64_t ip = 0; ip < npc; ++ip) {
      const double* row = &spec.pc_rows[static_cast<std::size_t>(ip * 5)];
      g.pc_positions.insert(g.pc_positions.end(), {row[0], row[1], row[2]});
      g.pc_charges.push_back(row[3]);
      g.pc_hardnesses.push_back(row[4]);
    }
  }

  std::vector<std::int32_t> atomic_numbers;
  atomic_numbers.reserve(static_cast<std::size_t>(total_atoms));
  for (const CaseSpec& spec : specs_) {
    atomic_numbers.insert(atomic_numbers.end(), spec.atomic_numbers.begin(),
                          spec.atomic_numbers.end());
  }

  gpuxtb_status_t s = make_basis_plan(g.batch_size, total_atoms, g.atom_offsets.data(),
                                      atomic_numbers.data(), g.basis, err);
  if (s) return s;
  s = make_integral_plan(g.basis, g.integrals, err);
  if (s) return s;
  s = make_h0_plan(g.basis, g.integrals, atomic_numbers.data(), g.h0_plan, err);
  if (s) return s;
  s = make_wavefunction_layout(g.basis, atomic_numbers.data(), g.molecular_charges.data(),
                               g.unpaired.data(), g.spins.data(), g.layout, err);
  if (s) return s;
  s = make_es2_plan(g.basis, atomic_numbers.data(), g.es2_plan, err);
  if (s) return s;
  s = make_es3_plan(g.basis, atomic_numbers.data(), g.es3_plan, err);
  if (s) return s;
  s = make_aes2_plan(g.basis, atomic_numbers.data(), g.aes2_plan, err);
  if (s) return s;
  s = make_mulliken_plan(g.basis, g.integrals, g.layout, g.mulliken_plan, err);
  if (s) return s;
  s = make_eigensolver_plan(g.layout, g.eig_plan, err);
  if (s) return s;
  s = make_coordination_plan(g.batch_size, total_atoms, g.atom_offsets.data(),
                             atomic_numbers.data(), g.coordination_plan, err);
  if (s) return s;
  if (total_point_charges > 0) {
    s = make_external_point_charge_plan(g.basis, atomic_numbers.data(), total_point_charges,
                                        g.pc_offsets.data(), g.pc_plan, err);
    if (s) return s;
  }
  s = make_d4_plan(g.batch_size, total_atoms, g.atom_offsets.data(), atomic_numbers.data(),
                   g.d4_plan, err);
  if (s) return s;

  const std::size_t matrix = static_cast<std::size_t>(g.integrals.total_matrix_elements);
  g.overlap.assign(matrix, 0.0);
  g.dint.assign(3 * matrix, 0.0);
  g.qint.assign(6 * matrix, 0.0);
  g.h0.assign(matrix, 0.0);
  g.cn.assign(static_cast<std::size_t>(total_atoms), 0.0);
  if (g.iscratch.size < g.integrals.workspace_size_bytes) return GPUXTB_STATUS_ALLOCATION_FAILED;
  s = evaluate_coordination_cpu(g.coordination_plan, g.positions.data(), g.cn.data(), err);
  if (s) return s;
  s = evaluate_overlap_cpu(g.basis, g.integrals, g.positions.data(), g.overlap.data(),
                           g.iscratch.data, g.iscratch.size, err);
  if (s) return s;
  s = evaluate_multipole_cpu(g.basis, g.integrals, g.positions.data(), g.dint.data(),
                             g.qint.data(), g.iscratch.data, g.iscratch.size, err);
  if (s) return s;
  s = evaluate_h0_cpu(g.basis, g.integrals, g.h0_plan, g.positions.data(), g.cn.data(),
                      g.overlap.data(), g.h0.data(), err);
  if (s) return s;

  const std::size_t e2n = static_cast<std::size_t>(g.es2_plan.total_matrix_elements());
  if (g.e2s.size < e2n * sizeof(double)) return GPUXTB_STATUS_ALLOCATION_FAILED;
  g.es2_ws.matrix_scratch = static_cast<double*>(g.e2scratch.data);
  g.es2_ws.matrix_elements = g.es2_plan.total_matrix_elements();
  s = update_es2_geometry_cache_cpu(g.es2_plan, g.positions.data(), 1u,
                                    static_cast<double*>(g.e2s.data), e2n, g.es2_ws, g.es2_cache,
                                    err);
  if (s) return s;

  const std::size_t a2n = static_cast<std::size_t>(g.aes2_plan.pair_data_elements());
  if (g.a2s.size < a2n * sizeof(double)) return GPUXTB_STATUS_ALLOCATION_FAILED;
  g.aes2_ws.pair_scratch = static_cast<double*>(g.a2scratch.data);
  g.aes2_ws.pair_elements = g.aes2_plan.pair_data_elements();
  s = update_aes2_geometry_cache_cpu(g.aes2_plan, g.positions.data(), g.cn.data(), 1u,
                                     static_cast<double*>(g.a2s.data), a2n, g.aes2_ws, g.aes2_cache,
                                     err);
  if (s) return s;

  if (g.d4_buffer.size < g.d4_plan.workspace_size_bytes()) return GPUXTB_STATUS_ALLOCATION_FAILED;
  s = bind_d4_workspace(g.d4_plan, g.d4_buffer.data, g.d4_buffer.size, g.d4_ws, err);
  if (s) return s;
  g.d4_pairs.assign(static_cast<std::size_t>(g.d4_plan.total_pairs()) * kD4PairDataElements, 0.0);
  g.d4_coordination.assign(static_cast<std::size_t>(g.d4_plan.total_atoms()), 0.0);
  s = update_d4_geometry_cache_cpu(g.d4_plan, g.positions.data(), 1u, g.d4_pairs.data(),
                                   g.d4_pairs.size(), g.d4_coordination.data(),
                                   g.d4_coordination.size(), g.d4_ws, g.d4_cache, err);
  if (s) return s;

  if (total_point_charges > 0) {
    g.pc_shell_potential.assign(static_cast<std::size_t>(g.basis.total_shells), 0.0);
    s = evaluate_external_point_charge_potential_cpu(
        g.pc_plan, g.positions.data(), g.pc_positions.data(), g.pc_charges.data(),
        g.pc_hardnesses.data(), g.pc_shell_potential.data(), err);
    if (s) return s;
  }

  g.geom.h0 = g.h0.data();
  g.geom.h0_elements = static_cast<std::int64_t>(g.h0.size());
  g.geom.integrals = {g.overlap.data(), g.dint.data(), g.qint.data(),
                      g.integrals.total_matrix_elements, g.mulliken_plan.identity()};
  g.geom.es2_cache = g.es2_cache;
  g.geom.aes2_cache = g.aes2_cache;
  g.geom.d4_cache = g.d4_cache;
  g.geom.geometry_generation = 1u;
  if (total_point_charges > 0) {
    g.geom.explicit_point_charge_shell_potential = g.pc_shell_potential.data();
    g.geom.explicit_point_charge_shell_elements =
        static_cast<std::int64_t>(g.pc_shell_potential.size());
  }

  s = make_mkl_rt_lp64_backend(g.backend, err);
  if (s) return s;
  if (g.wfn_s.size < g.layout.workspace_size_bytes) return GPUXTB_STATUS_ALLOCATION_FAILED;
  s = bind_wavefunction_view(g.layout, g.wfn_s.data, g.wfn_s.size, g.wfn, err);
  if (s) return s;
  // Issue #49 closed-loop trajectories start from the same initial guess as
  // the pinned golden: tblite's new_wavefunction leaves the SCC perturbative
  // q/d/Q state at exactly zero.  The production SAD seed would otherwise move
  // the first mixed state (and for charged h3_plus the first ES2/ES3
  // potentials) away from the golden trajectory.
  s = initialize_sad_multipole_state(g.layout, g.wfn, err);
  if (s) return s;
  std::fill_n(g.wfn.qsh, static_cast<std::size_t>(g.layout.qsh.element_count), 0.0);
  std::fill_n(g.wfn.qat, static_cast<std::size_t>(g.layout.qat.element_count), 0.0);
  std::fill_n(g.wfn.dipole, static_cast<std::size_t>(g.layout.dipole.element_count), 0.0);
  std::fill_n(g.wfn.quadrupole, static_cast<std::size_t>(g.layout.quadrupole.element_count), 0.0);

  if (g.oc_s.size < g.eig_plan.overlap_cache_size_bytes()) return GPUXTB_STATUS_ALLOCATION_FAILED;
  s = bind_eigensolver_overlap_cache(g.eig_plan, g.oc_s.data, g.oc_s.size, g.ocache, err);
  if (s) return s;
  if (g.eig_s.size < g.eig_plan.workspace_size_bytes()) return GPUXTB_STATUS_ALLOCATION_FAILED;
  s = bind_eigensolver_workspace(g.eig_plan, g.eig_s.data, g.eig_s.size, g.eig_ws, err);
  if (s) return s;
  s = factor_overlap_cpu(g.eig_plan, g.overlap.data(), 1u, g.backend, g.eig_ws, g.ocache, err);
  if (s) return s;

  geometry_ = std::move(geometry);
  err.clear();
  return GPUXTB_STATUS_SUCCESS;
}

gpuxtb_status_t TraceBatch::build_stage(const CaseSpec& reference, std::string& err) {
  Geometry& g = *geometry_;
  auto stage = std::make_shared<Stage>();
  gpuxtb_status_t s = make_scc_mixer_plan(g.layout, reference.mixer_memory, reference.mixer_damping,
                                          kTbliteRmsTolerance, kTbliteRmsTolerance,
                                          stage->mixer_plan, err);
  if (s) return s;
  s = make_scc_driver_plan(g.layout, g.mulliken_plan, g.es2_plan, g.es3_plan, g.aes2_plan,
                           g.eig_plan, stage->mixer_plan, &g.d4_plan, nullptr,
                           kMaximumHarnessIterations,
                           reference.temperature_kelvin * kKelvinToHartree, kTbliteEnergyTolerance,
                           stage->driver_plan, err);
  if (s) return s;
  if (stage->mixer_s.size < stage->mixer_plan.state_size_bytes()) {
    return GPUXTB_STATUS_ALLOCATION_FAILED;
  }
  s = bind_scc_mixer_state(stage->mixer_plan, stage->mixer_s.data, stage->mixer_s.size,
                           stage->mixer_state, err);
  if (s) return s;
  if (stage->drv_s.size < stage->driver_plan.state_size_bytes()) {
    return GPUXTB_STATUS_ALLOCATION_FAILED;
  }
  s = bind_scc_driver_state(stage->driver_plan, stage->drv_s.data, stage->drv_s.size,
                            stage->driver_state, err);
  if (s) return s;
  if (stage->drvws_s.size < stage->driver_plan.workspace_size_bytes()) {
    return GPUXTB_STATUS_ALLOCATION_FAILED;
  }
  s = bind_scc_driver_workspace(stage->driver_plan, stage->drvws_s.data, stage->drvws_s.size,
                                stage->drv_ws, err);
  if (s) return s;
  s = initialize_scc_driver_state_cpu(stage->driver_plan, g.wfn, stage->mixer_state,
                                      stage->driver_state, err);
  if (s) return s;
  stage_ = std::move(stage);
  iterations_.assign(static_cast<std::size_t>(g.batch_size), {});
  err.clear();
  return GPUXTB_STATUS_SUCCESS;
}

gpuxtb_status_t TraceBatch::build(std::string& err) {
  gpuxtb_status_t s = build_geometry(err);
  if (s) return s;
  return build_stage(specs_.front(), err);
}

void TraceBatch::poison_h0(std::int64_t system) {
  Geometry& g = *geometry_;
  const std::int64_t matrix_begin = g.mulliken_plan.matrix_offsets()[system];
  const std::int64_t matrix_end = g.mulliken_plan.matrix_offsets()[system + 1u];
  for (std::int64_t element = matrix_begin; element < matrix_end; ++element) {
    g.h0[static_cast<std::size_t>(element)] = std::numeric_limits<double>::quiet_NaN();
  }
}

gpuxtb_status_t TraceBatch::inject_mixed_state(std::int64_t system, const std::string& state_path,
                                               std::string& err) {
  Geometry& g = *geometry_;
  const std::int64_t shell_begin = g.basis.batch_shell_offsets[system];
  const std::int64_t shell_end = g.basis.batch_shell_offsets[system + 1u];
  const std::int64_t qat_begin = g.layout.qat.system_offsets[system];
  const std::int64_t qat_end = g.layout.qat.system_offsets[system + 1u];
  const std::int64_t atom_begin = g.layout.atom_offsets[system];
  const std::int64_t atom_end = g.layout.atom_offsets[system + 1u];
  const std::int64_t dip_base = g.layout.dipole.system_offsets[system];
  const std::int64_t quad_base = g.layout.quadrupole.system_offsets[system];
  const std::int64_t shells = shell_end - shell_begin;
  const std::int64_t atoms = atom_end - atom_begin;

  std::ifstream file(state_path);
  if (!file) {
    err = "cannot open state file " + state_path;
    return GPUXTB_STATUS_INVALID_ARGUMENT;
  }
  double value = 0.0;
  std::int64_t count = 0;

  auto read_section = [&](const char* label, std::int64_t expected) -> bool {
    std::string token;
    if (!(file >> token) || token != label) {
      err = std::string("state file missing section ") + label;
      return false;
    }
    if (!(file >> count) || count != expected) {
      err = std::string("state file ") + label + " has wrong count";
      return false;
    }
    return true;
  };
  if (!read_section("qsh", shells)) return GPUXTB_STATUS_INVALID_ARGUMENT;
  for (std::int64_t local = 0; local < shells; ++local) {
    if (!(file >> value) || !std::isfinite(value)) {
      err = "state file qsh value malformed";
      return GPUXTB_STATUS_INVALID_ARGUMENT;
    }
    g.wfn.qsh[shell_begin + local] = value;
  }
  if (!read_section("qat", atoms)) return GPUXTB_STATUS_INVALID_ARGUMENT;
  for (std::int64_t local = 0; local < atoms; ++local) {
    if (!(file >> value) || !std::isfinite(value)) {
      err = "state file qat value malformed";
      return GPUXTB_STATUS_INVALID_ARGUMENT;
    }
    g.wfn.qat[qat_begin + local] = value;
  }
  if (!read_section("dipoles", 3 * atoms)) return GPUXTB_STATUS_INVALID_ARGUMENT;
  for (std::int64_t local = 0; local < 3 * atoms; ++local) {
    if (!(file >> value) || !std::isfinite(value)) {
      err = "state file dipole value malformed";
      return GPUXTB_STATUS_INVALID_ARGUMENT;
    }
    g.wfn.dipole[dip_base + local] = value;
  }
  if (!read_section("quadrupoles", 6 * atoms)) return GPUXTB_STATUS_INVALID_ARGUMENT;
  for (std::int64_t local = 0; local < 6 * atoms; ++local) {
    if (!(file >> value) || !std::isfinite(value)) {
      err = "state file quadrupole value malformed";
      return GPUXTB_STATUS_INVALID_ARGUMENT;
    }
    g.wfn.quadrupole[quad_base + local] = value;
  }
  err.clear();
  return GPUXTB_STATUS_SUCCESS;
}

void TraceBatch::set_replay_context(std::int64_t system, std::uint64_t logical_index,
                                    double previous_energy) {
  // The driver computes the energy change as (new - old) where old is
  // state.free_energies once iterations > 0.  Seeding the logical iteration
  // and previous internal energy reproduces tblite's energy_delta and
  // econverged flag for golden iteration logical_index.
  if (logical_index > 1u) {
    stage_->driver_state.iterations[system] = logical_index - 1u;
    stage_->driver_state.free_energies[system] = previous_energy;
  }
}

gpuxtb_status_t TraceBatch::step(std::string& err) {
  return iterate_scc_driver_batch_cpu(stage_->driver_plan, geometry_->geom, geometry_->backend,
                                      geometry_->ocache, geometry_->wfn, stage_->mixer_state,
                                      stage_->driver_state, stage_->drv_ws, err);
}

gpuxtb_status_t TraceBatch::step_once(std::string& err) {
  capture_mixed_pre_step();
  const gpuxtb_status_t status = step(err);
  if (status != GPUXTB_STATUS_SUCCESS && status != GPUXTB_STATUS_SCC_NOT_CONVERGED &&
      status != GPUXTB_STATUS_EIGENSOLVER_FAILED && status != GPUXTB_STATUS_INTERNAL_ERROR) {
    return status;
  }
  record_iteration_snapshots();
  return GPUXTB_STATUS_SUCCESS;
}

gpuxtb_status_t TraceBatch::restart_mixer_system(std::int64_t system, std::string& err) {
  return restart_scc_mixer_system_cpu(stage_->mixer_plan, system, geometry_->wfn,
                                      stage_->mixer_state, err);
}

gpuxtb_status_t TraceBatch::run(std::string& err) {
  Geometry& g = *geometry_;
  const std::int64_t batch = g.batch_size;
  for (std::uint64_t total = 0u; total < kMaximumHarnessIterations; ++total) {
    bool any_active = false;
    for (std::int64_t system = 0; system < batch; ++system) {
      const bool active = stage_->driver_state.system_statuses[system] == GPUXTB_STATUS_SUCCESS &&
                          stage_->driver_state.converged[system] == 0u;
      any_active = any_active || active;
    }
    if (!any_active) {
      break;
    }
    capture_mixed_pre_step();
    const gpuxtb_status_t step_status = step(err);
    if (step_status != GPUXTB_STATUS_SUCCESS && step_status != GPUXTB_STATUS_SCC_NOT_CONVERGED &&
        step_status != GPUXTB_STATUS_EIGENSOLVER_FAILED &&
        step_status != GPUXTB_STATUS_INTERNAL_ERROR) {
      // Structural/binding failures are whole-call and abort the batch.
      return step_status;
    }
    record_iteration_snapshots();
  }
  err.clear();
  return GPUXTB_STATUS_SUCCESS;
}

void TraceBatch::capture_mixed_pre_step() {
  Geometry& g = *geometry_;
  const std::int64_t batch = g.batch_size;
  pending_mixed_.assign(static_cast<std::size_t>(batch),
                        std::vector<std::vector<double>>(4u));
  for (std::int64_t system = 0; system < batch; ++system) {
    if (stage_->driver_state.system_statuses[system] != GPUXTB_STATUS_SUCCESS ||
        stage_->driver_state.converged[system] != 0u) {
      continue;
    }
    const std::int64_t shell_begin = g.basis.batch_shell_offsets[system];
    const std::int64_t shell_end = g.basis.batch_shell_offsets[system + 1u];
    const std::int64_t qat_begin = g.layout.qat.system_offsets[system];
    const std::int64_t qat_end = g.layout.qat.system_offsets[system + 1u];
    const std::int64_t dip_begin = g.layout.dipole.system_offsets[system];
    const std::int64_t dip_end = g.layout.dipole.system_offsets[system + 1u];
    const std::int64_t quad_begin = g.layout.quadrupole.system_offsets[system];
    const std::int64_t quad_end = g.layout.quadrupole.system_offsets[system + 1u];
    pending_mixed_[static_cast<std::size_t>(system)][0u].assign(g.wfn.qsh + shell_begin,
                                                                g.wfn.qsh + shell_end);
    pending_mixed_[static_cast<std::size_t>(system)][1u].assign(g.wfn.qat + qat_begin,
                                                                g.wfn.qat + qat_end);
    pending_mixed_[static_cast<std::size_t>(system)][2u].assign(g.wfn.dipole + dip_begin,
                                                                g.wfn.dipole + dip_end);
    pending_mixed_[static_cast<std::size_t>(system)][3u].assign(g.wfn.quadrupole + quad_begin,
                                                                g.wfn.quadrupole + quad_end);
  }
}

void TraceBatch::record_iteration_snapshots() {
  Geometry& g = *geometry_;
  Stage& st = *stage_;
  const std::int64_t batch = g.batch_size;
  for (std::int64_t system = 0; system < batch; ++system) {
    // Lanes that did not advance (terminal or newly failed) contribute no
    // iteration snapshot.
    const std::uint64_t old_count =
        static_cast<std::uint64_t>(iterations_[static_cast<std::size_t>(system)].size());
    if (st.driver_state.iterations[system] <= old_count) {
      continue;
    }
    if (st.driver_state.system_statuses[system] != GPUXTB_STATUS_SUCCESS &&
        st.driver_state.system_statuses[system] != GPUXTB_STATUS_SCC_NOT_CONVERGED) {
      continue;
    }
    CapturedIteration row;
    const std::int64_t shell_begin = g.basis.batch_shell_offsets[system];
    const std::int64_t shell_end = g.basis.batch_shell_offsets[system + 1u];
    const std::int64_t qat_begin = g.layout.qat.system_offsets[system];
    const std::int64_t qat_end = g.layout.qat.system_offsets[system + 1u];
    const std::int64_t dip_begin = g.layout.dipole.system_offsets[system];
    const std::int64_t dip_end = g.layout.dipole.system_offsets[system + 1u];
    const std::int64_t quad_begin = g.layout.quadrupole.system_offsets[system];
    const std::int64_t quad_end = g.layout.quadrupole.system_offsets[system + 1u];
    const std::int64_t density_base = g.layout.density.system_offsets[system];
    const std::int64_t eig_begin = g.layout.eigenvalues.system_offsets[system];
    const std::int64_t occ_begin = g.layout.occupations.system_offsets[system];

    // Mixed q/d/Q are the pre-solve wavefunction state captured before the
    // driver call; the wavefunction now holds the mixer's next input.
    row.mixed_qsh = std::move(pending_mixed_[static_cast<std::size_t>(system)][0u]);
    row.mixed_qat = std::move(pending_mixed_[static_cast<std::size_t>(system)][1u]);
    row.mixed_dipoles = std::move(pending_mixed_[static_cast<std::size_t>(system)][2u]);
    row.mixed_quadrupoles = std::move(pending_mixed_[static_cast<std::size_t>(system)][3u]);

    const std::int64_t matrix_begin = g.mulliken_plan.matrix_offsets()[system];
    const std::int64_t matrix_end = g.mulliken_plan.matrix_offsets()[system + 1u];
    const std::int64_t system_nao =
        g.layout.eigenvalues.system_offsets[system + 1u] - eig_begin;
    row.hamiltonian.assign(st.drv_ws.hamiltonian + density_base,
                           st.drv_ws.hamiltonian + density_base + (matrix_end - matrix_begin));
    row.density.assign(st.drv_ws.staged_wavefunction.density + density_base,
                       st.drv_ws.staged_wavefunction.density + density_base +
                           (matrix_end - matrix_begin));
    row.eigenvalues.assign(st.drv_ws.staged_wavefunction.eigenvalues + eig_begin,
                           st.drv_ws.staged_wavefunction.eigenvalues + eig_begin + system_nao);
    row.occupations_alpha.assign(st.drv_ws.staged_wavefunction.occupations + occ_begin,
                                 st.drv_ws.staged_wavefunction.occupations + occ_begin +
                                     system_nao);
    // Restricted: both channels share the same orbital occupations.
    row.occupations_beta = row.occupations_alpha;

    row.raw_qsh.assign(st.drv_ws.raw_qsh + shell_begin, st.drv_ws.raw_qsh + shell_end);
    row.raw_qat.assign(st.drv_ws.raw_qat + qat_begin, st.drv_ws.raw_qat + qat_end);
    row.raw_dipoles.assign(st.drv_ws.raw_dipoles + dip_begin, st.drv_ws.raw_dipoles + dip_end);
    row.raw_quadrupoles.assign(st.drv_ws.raw_quadrupoles + quad_begin,
                               st.drv_ws.raw_quadrupoles + quad_end);

    if (!g.pc_shell_potential.empty()) {
      row.point_charge_shell_potential.assign(
          g.pc_shell_potential.begin() + shell_begin, g.pc_shell_potential.begin() + shell_end);
      row.point_charge_energy.resize(static_cast<std::size_t>(shell_end - shell_begin));
      for (std::int64_t sh = shell_begin; sh < shell_end; ++sh) {
        row.point_charge_energy[static_cast<std::size_t>(sh - shell_begin)] =
            row.raw_qsh[static_cast<std::size_t>(sh - shell_begin)] *
            g.pc_shell_potential[static_cast<std::size_t>(sh)];
      }
    }

    row.energy = st.driver_state.internal_energies[system];
    row.energy_delta = st.driver_state.free_energy_changes[system];
    row.residual_rms = st.drv_ws.staged_mixer_state.residual_rms[system];
    row.econv = std::abs(row.energy_delta) < st.driver_plan.energy_tolerance() ? 1 : 0;
    row.pconv = row.residual_rms < st.mixer_plan.rms_tolerance() ? 1 : 0;
    row.conv = st.driver_state.converged[system] ? 1 : 0;
    iterations_[static_cast<std::size_t>(system)].push_back(std::move(row));
  }
}

void emit_value(std::ostream& output, double value) {
  output << std::setprecision(17) << std::scientific << value << "\n";
}
void emit_int(std::ostream& output, std::int64_t value) { output << value << "\n"; }

void TraceBatch::emit(std::ostream& output, std::int64_t system) const {
  const Geometry& g = *geometry_;
  const std::vector<CapturedIteration>& rows =
      iterations_[static_cast<std::size_t>(system)];
  const CaseSpec& spec = specs_[static_cast<std::size_t>(system)];
  const std::int64_t nat = spec.nat;
  const std::int64_t nsh = g.basis.batch_shell_offsets[system + 1] -
                           g.basis.batch_shell_offsets[system];
  // Eigenvalue system offsets are per-orbital, so their span is nao (the
  // density offsets are matrix elements, nao*nao).
  const std::int64_t nao = g.layout.eigenvalues.system_offsets[system + 1] -
                           g.layout.eigenvalues.system_offsets[system];
  const std::int64_t matrix_begin = g.mulliken_plan.matrix_offsets()[system];
  const std::int64_t matrix_end = g.mulliken_plan.matrix_offsets()[system + 1u];
  const std::int64_t atom_begin = g.layout.atom_offsets[system];
  const std::int64_t npc = static_cast<std::int64_t>(spec.pc_rows.size() / 5u);
  const std::int64_t niterations = static_cast<std::int64_t>(rows.size());
  const std::int64_t terminal = (niterations > 0 && rows.back().conv) ? 1 : 2;

  output << "nat " << nat << " nsh " << nsh << " nao " << nao << " niterations " << niterations
         << " terminal " << terminal << "\n";
  output << "atomic_numbers\n";
  for (std::int64_t i = 0; i < nat; ++i) emit_int(output, spec.atomic_numbers[static_cast<std::size_t>(i)]);
  output << "positions\n";
  for (std::int64_t i = 0; i < nat; ++i) {
    emit_value(output, g.positions[static_cast<std::size_t>((atom_begin + i) * 3)]);
    emit_value(output, g.positions[static_cast<std::size_t>((atom_begin + i) * 3 + 1)]);
    emit_value(output, g.positions[static_cast<std::size_t>((atom_begin + i) * 3 + 2)]);
  }
  output << "molecular_charge\n";
  emit_value(output, spec.molecular_charge);
  output << "unpaired_electrons\n";
  emit_int(output, spec.unpaired_electrons);
  output << "temperature\n";
  emit_value(output, spec.temperature_kelvin);
  output << "n_point_charges\n";
  emit_int(output, npc);
  for (std::int64_t ip = 0; ip < npc; ++ip) {
    const double* row = &spec.pc_rows[static_cast<std::size_t>(ip * 5)];
    for (std::int64_t j = 0; j < 5; ++j) emit_value(output, row[j]);
  }
  output << "atom_to_shell_count\n";
  for (std::int64_t i = 0; i < nat; ++i) {
    const std::int64_t pos = static_cast<std::int64_t>(g.basis.atom_shell_offsets[atom_begin + i]);
    const std::int64_t end = static_cast<std::int64_t>(
        g.basis.atom_shell_offsets[atom_begin + i + 1]);
    emit_int(output, end - pos);
  }

  output << "overlap\n";
  for (std::int64_t col = 0; col < nao; ++col)
    for (std::int64_t row = 0; row < nao; ++row)
      emit_value(output, g.overlap[static_cast<std::size_t>(matrix_begin + col * nao + row)]);
  output << "core_hamiltonian\n";
  for (std::int64_t col = 0; col < nao; ++col)
    for (std::int64_t row = 0; row < nao; ++row)
      emit_value(output, g.h0[static_cast<std::size_t>(matrix_begin + col * nao + row)]);

  for (std::int64_t i = 0; i < niterations; ++i) {
    const CapturedIteration& row = rows[static_cast<std::size_t>(i)];
    output << "iteration\n";
    emit_int(output, i + 1);
    output << "hamiltonian\n";
    for (std::int64_t col = 0; col < nao; ++col)
      for (std::int64_t r = 0; r < nao; ++r)
        emit_value(output, row.hamiltonian[static_cast<std::size_t>(col * nao + r)]);
    output << "eigenvalues\n";
    for (double v : row.eigenvalues) emit_value(output, v);
    output << "occupations\n";
    for (double v : row.occupations_alpha) emit_value(output, v);
    for (double v : row.occupations_beta) emit_value(output, v);
    output << "density\n";
    for (std::int64_t col = 0; col < nao; ++col)
      for (std::int64_t r = 0; r < nao; ++r)
        emit_value(output, row.density[static_cast<std::size_t>(col * nao + r)]);
    output << "mixed_qsh\n";
    for (double v : row.mixed_qsh) emit_value(output, v);
    output << "mixed_qat\n";
    for (double v : row.mixed_qat) emit_value(output, v);
    output << "mixed_dipoles\n";
    for (double v : row.mixed_dipoles) emit_value(output, v);
    output << "mixed_quadrupoles\n";
    for (double v : row.mixed_quadrupoles) emit_value(output, v);
    output << "raw_qsh\n";
    for (double v : row.raw_qsh) emit_value(output, v);
    output << "raw_qat\n";
    for (double v : row.raw_qat) emit_value(output, v);
    output << "raw_dipoles\n";
    for (double v : row.raw_dipoles) emit_value(output, v);
    output << "raw_quadrupoles\n";
    for (double v : row.raw_quadrupoles) emit_value(output, v);
    if (npc > 0) {
      output << "point_charge_shell_potential\n";
      for (double v : row.point_charge_shell_potential) emit_value(output, v);
      output << "point_charge_energy\n";
      for (double v : row.point_charge_energy) emit_value(output, v);
    }
    output << "energy\n";
    emit_value(output, row.energy);
    output << "energy_delta\n";
    emit_value(output, row.energy_delta);
    output << "residual_rms\n";
    emit_value(output, row.residual_rms);
    output << "convergence\n";
    emit_int(output, row.econv);
    emit_int(output, row.pconv);
    emit_int(output, row.tconv);
    emit_int(output, row.conv);
  }
}

}  // namespace gpuxtb_trace_harness

#endif  // GPUXTB_TESTS_SUPPORT_SCC_TRACE_HARNESS_HPP